package global

const (
	SUCCESS        = 200
	ERROR          = 500
	INVALID_PARAMS = 400

	ERROR_EXIST_TAG       = 10001
	ERROR_EXIST_TAG_FAIL  = 10002
	ERROR_NOT_EXIST_TAG   = 10003
	ERROR_GET_TAGS_FAIL   = 10004
	ERROR_COUNT_TAG_FAIL  = 10005
	ERROR_ADD_TAG_FAIL    = 10006
	ERROR_EDIT_TAG_FAIL   = 10007
	ERROR_DELETE_TAG_FAIL = 10008
	ERROR_EXPORT_TAG_FAIL = 10009
	ERROR_IMPORT_TAG_FAIL = 10010

	ERROR_NOT_EXIST_ARTICLE        = 10011
	ERROR_CHECK_EXIST_ARTICLE_FAIL = 10012
	ERROR_ADD_ARTICLE_FAIL         = 10013
	ERROR_DELETE_ARTICLE_FAIL      = 10014
	ERROR_EDIT_ARTICLE_FAIL        = 10015
	ERROR_COUNT_ARTICLE_FAIL       = 10016
	ERROR_GET_ARTICLES_FAIL        = 10017
	ERROR_GET_ARTICLE_FAIL         = 10018
	ERROR_GEN_ARTICLE_POSTER_FAIL  = 10019

	ERROR_AUTH_CHECK_TOKEN_FAIL   = 20001
	ERROR_AUTH_CHECK_TOKEN_EXPIRE = 20002
	ERROR_AUTH_CHECK_TOKEN_FORMAT = 20003
	ERROR_AUTH_TOKEN_NOT_EXIST    = 20004
	ERROR_AUTH_TOKEN_GEN          = 20005
	ERROR_AUTH                    = 20006

	ERROR_DB_INIT_FAIL   = 30001
	ERROR_DB_QUERY_FAIL  = 30002
	ERROR_DB_INSERT_FAIL = 30003
	ERROR_DB_UPDATE_FAIL = 30004
	ERROR_DB_DELETE_FAIL = 30005

	ERROR_BODY_NOT_EXIST        = 40001
	ERROR_BODY_PARSE_FAIL       = 40002
	ERROR_BODY_VALUE_CHECK_FAIL = 40003
)

var Msgs = map[int]string{
	SUCCESS:                        "ok",
	ERROR:                          "fail",
	INVALID_PARAMS:                 "请求参数错误",
	ERROR_EXIST_TAG:                "已存在该标签名称",
	ERROR_EXIST_TAG_FAIL:           "获取已存在标签失败",
	ERROR_NOT_EXIST_TAG:            "该标签不存在",
	ERROR_GET_TAGS_FAIL:            "获取所有标签失败",
	ERROR_COUNT_TAG_FAIL:           "统计标签失败",
	ERROR_ADD_TAG_FAIL:             "新增标签失败",
	ERROR_EDIT_TAG_FAIL:            "修改标签失败",
	ERROR_DELETE_TAG_FAIL:          "删除标签失败",
	ERROR_EXPORT_TAG_FAIL:          "导出标签失败",
	ERROR_IMPORT_TAG_FAIL:          "导入标签失败",
	ERROR_NOT_EXIST_ARTICLE:        "该文章不存在",
	ERROR_ADD_ARTICLE_FAIL:         "新增文章失败",
	ERROR_DELETE_ARTICLE_FAIL:      "删除文章失败",
	ERROR_CHECK_EXIST_ARTICLE_FAIL: "检查文章是否存在失败",
	ERROR_EDIT_ARTICLE_FAIL:        "修改文章失败",
	ERROR_COUNT_ARTICLE_FAIL:       "统计文章失败",
	ERROR_GET_ARTICLES_FAIL:        "获取多个文章失败",
	ERROR_GET_ARTICLE_FAIL:         "获取单个文章失败",
	ERROR_GEN_ARTICLE_POSTER_FAIL:  "生成文章海报失败",
	ERROR_AUTH_CHECK_TOKEN_FAIL:    "Token鉴权失败",
	ERROR_AUTH_CHECK_TOKEN_EXPIRE:  "Token已过期",
	ERROR_AUTH_CHECK_TOKEN_FORMAT:  "Token格式错误",
	ERROR_AUTH_TOKEN_NOT_EXIST:     "Token不存在",
	ERROR_AUTH_TOKEN_GEN:           "Token生成失败",
	ERROR_AUTH:                     "Token错误",
	ERROR_DB_INIT_FAIL:             "数据表初始化失败",
	ERROR_DB_QUERY_FAIL:            "数据行查询失败",
	ERROR_DB_INSERT_FAIL:           "数据行插入失败",
	ERROR_DB_UPDATE_FAIL:           "数据行更新失败",
	ERROR_DB_DELETE_FAIL:           "数据行删除失败",
	ERROR_BODY_NOT_EXIST:           "请求体为空",
	ERROR_BODY_PARSE_FAIL:          "请求体解析失败",
	ERROR_BODY_VALUE_CHECK_FAIL:    "请求体数据参数检查失败",
}
