{
 "title": "Alertmanager",
 "description": "Dashboard showing Prometheus Alertmanager metrics for observing status of the cluster and possible debbuging.",
 "tags": [ "alertmanager" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "query_result(alertmanager_build_info)"
   },
   {
    "name": "statefulset",
    "label": "statefulset",
    "query": "query_result(kube_statefulset_labels)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Alertmanager Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alertmanager Instance Status",
   "type": "table",
   "description": "当前alertmanager实例的状态",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "time() - (alertmanager_build_info{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"} * on (instance, cluster) group_left process_start_time_seconds{})"
    },
    {
     "expr": "time() - alertmanager_config_last_reload_success_timestamp_seconds{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}"
    },
    {
     "expr": "alertmanager_config_last_reload_successful{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}"
    }
   ]
  },
  {
   "title": "Cluster Size",
   "type": "singlestat",
   "description": "当前alertmanager集群的实例数",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(alertmanager_cluster_members{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"})"
    }
   ]
  },
  {
   "title": "Notify Failed",
   "type": "singlestat",
   "description": "12小时内失败的通知数量",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(alertmanager_notifications_failed_total - alertmanager_notifications_failed_total offset 12h)"
    }
   ]
  },
  {
   "title": "Active alerts",
   "type": "singlestat",
   "description": "当前处于告警状态的告警数",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(alertmanager_alerts{state=\"active\", namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"})"
    }
   ]
  },
  {
   "title": "Suppressed Alerts",
   "type": "singlestat",
   "description": "当前被抑制的告警数",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(alertmanager_alerts{state=\"suppressed\", namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"})"
    }
   ]
  },
  {
   "title": "Active Silences",
   "type": "singlestat",
   "description": "当前alertmanager集群活跃的Silences数量",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(alertmanager_silences{state=\"active\", namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"})"
    }
   ]
  },
  {
   "title": "CPU Utilization of Pod",
   "type": "graph",
   "description": "Prometheus实例的CPU使用率",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (container_cpu_usage_seconds_total_irate5m{namespace=~\"$namespace\",pod_name=~\"$statefulset-[0-9]{1,3}\",image!=\"\",container_name!=\"POD\"}) / sum by (pod_name) (container_spec_cpu_quota{namespace=~\"$namespace\",pod_name=~\"$statefulset-[0-9]{1,3}\",image!=\"\",container_name!=\"POD\"}) * 100000",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Utilization of Pod",
   "type": "graph",
   "description": "Prometheus实例的内存使用率",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (container_memory_usage_bytes_without_cache{namespace=\"$namespace\",pod_name=~\"$statefulset-[0-9]{1,3}\"}) / sum by (pod_name) (container_spec_memory_limit_bytes{namespace=\"$namespace\",pod_name=~\"$statefulset-[0-9]{1,3}\",image!=\"\",container_name!=\"POD\"})",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Network Transmit Rate of Pod",
   "type": "graph",
   "description": "各个实例过去5分钟的平均网络发送速率",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (container_network_transmit_bytes_total_irate5m{namespace=\"$namespace\", pod_name=~\"$statefulset-[0-9]{1,3}\"})",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Network Received Rate of Pod",
   "type": "graph",
   "description": "各个实例过去5分钟的平均网络接收速率",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (container_network_receive_bytes_total_irate5m{namespace=\"$namespace\",pod_name=~\"$statefulset-[0-9]{1,3}\"})",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Filesystem Read Rate of Pod",
   "type": "graph",
   "description": "各个实例过去5分钟的平均读取磁盘的速率",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (rate(container_fs_reads_bytes_total{namespace=\"$namespace\", pod_name=~\"$statefulset-[0-9]{1,3}\"}[5m]))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Filesystem Write Rate of Pod",
   "type": "graph",
   "description": "各个实例过去5分钟的平均写磁盘的速率",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (rate(container_fs_writes_bytes_total{namespace=\"$namespace\", pod_name=~\"$statefulset-[0-9]{1,3}\"}[5m]))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Alertmanager Notifications and Message",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }
  },
  {
   "title": "Notifications Count Sent by Alertmanager",
   "type": "graph",
   "description": "过去5分钟发送的通知消息数，按照发送状态与发送方式分组",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(alertmanager_notifications_total{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m])) by (integration)",
     "legendFormat": "Succeeded {{ integration}}"
    },
    {
     "expr": "sum(increase(alertmanager_notifications_failed_total{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m])) by (integration)",
     "legendFormat": "Failed {{ integration }}"
    }
   ]
  },
  {
   "title": "Notification Send Latency Group by Quantile",
   "type": "graph",
   "description": "过去5分钟内发送通知的平均延迟，按照延迟分布来分组",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(histogram_quantile(0.9,rate(alertmanager_notification_latency_seconds_bucket{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m]))) by (integration)",
     "legendFormat": " Latency 0.9q {{ integration }} "
    },
    {
     "expr": "sum(histogram_quantile(0.99,rate(alertmanager_notification_latency_seconds_bucket{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m]))) by (integration)",
     "legendFormat": "Latency 0.99q  {{ integration }}"
    }
   ]
  },
  {
   "title": "Alerts Count Group by State",
   "type": "graph",
   "description": "当前集群的告警数，按照告警的状态进行分组",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(alertmanager_alerts{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}) by (state)",
     "legendFormat": "Alerts {{state}}"
    }
   ]
  },
  {
   "title": "Received Aerts Count from Prometheus Group by Status",
   "type": "graph",
   "description": "当前集群过去5分钟内从Prometheus接收到告警消息，按照触发的告警的状态进行分组",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(alertmanager_alerts_received_total{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m])) by (status)",
     "legendFormat": "Received {{ status }}"
    }
   ]
  },
  {
   "title": "Cluster Messages Queued and Pruned",
   "type": "graph",
   "description": "当前集群当中排队的消息和处理的消息",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(alertmanager_cluster_messages_pruned_total{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"})",
     "legendFormat": "Pruned Messages"
    },
    {
     "expr": "avg(alertmanager_cluster_messages_queued{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"})",
     "legendFormat": "Queued Messages"
    }
   ]
  },
  {
   "title": "Request Count of Alert Manager",
   "type": "graph",
   "description": "过去5分钟内，Alert Manager的请求数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "alertmanager_http_request_duration_seconds_count{handler=\"/alerts\"} - alertmanager_http_request_duration_seconds_count{handler=\"/alerts\"} offset 5m",
     "legendFormat": "Pruned Messages"
    }
   ]
  },
  { "title": "Alertmanager Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Cluster Health Score",
   "type": "graph",
   "description": "当前集群的健康分数",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(alertmanager_cluster_health_score{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"})",
     "legendFormat": "Cluster Health Score"
    }
   ]
  },
  {
   "title": "Cluster Members Count",
   "type": "graph",
   "description": "当前集群的成员数和失败的节点数",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(alertmanager_cluster_members{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"})",
     "legendFormat": "Cluster Members"
    },
    {
     "expr": "avg(alertmanager_cluster_failed_peers{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"})",
     "legendFormat": "Failed Peers"
    }
   ]
  },
  {
   "title": "Cluster Peers Left and Joined",
   "type": "graph",
   "description": "当前集群过去5分钟内加入的节点和丢失的节点",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(increase(alertmanager_cluster_peers_left_total{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m]))",
     "legendFormat": "Cluster Joined Peers"
    },
    {
     "expr": "avg(increase(alertmanager_cluster_peers_joined_total{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m]))",
     "legendFormat": "Cluster Left Peers"
    }
   ]
  },
  {
   "title": "Cluster Reconnections",
   "type": "graph",
   "description": "当前集群过去5分钟内发生的实例重连次数",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(increase(alertmanager_cluster_reconnections_total{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m]))",
     "legendFormat": "Total Reconnections"
    },
    {
     "expr": "avg(increase(alertmanager_cluster_reconnections_failed_total{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m]))",
     "legendFormat": "Failed Reconnections"
    }
   ]
  },
  {
   "title": "Goroutines Group by Instance",
   "type": "graph",
   "description": "Prometheus实例的goroutines数量",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (pod) (go_goroutines{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"})",
     "legendFormat": "{{pod}}/goroutines"
    }
   ]
  },
  {
   "title": "GC Durations Group by Instance",
   "type": "graph",
   "description": "过去5分钟内Prometheus花在GC上的时间，按照实例进行分组",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (pod) (increase(go_gc_duration_seconds_sum{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m]))",
     "legendFormat": "{{pod}}/gc_durations"
    }
   ]
  }
 ]
}