{
 "title": "Elasticsearch Cluster Status",
 "description": "Elasticsearch Cluster Status Dashboard",
 "tags": [ "es" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": "label_values(es_cluster_nodes_number, cluster)"
   },
   {
    "name": "Node",
    "query": "label_values(es_fs_total_total_bytes{cluster=~\"$Cluster\"}, node)"
   },
   {
    "name": "Instance",
    "query": "label_values(es_fs_total_total_bytes{cluster=~\"$Cluster\", node=~\"$Node\"}, instance)"
   },
   {
    "name": "Index",
    "query": "label_values(es_index_replicas_number{cluster=\"$Cluster\"}, index)"
   },
   {
    "name": "DataNodeNum",
    "query": "query_result(topk(1, es_cluster_datanodes_number{cluster=\"$Cluster\"}))"
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "singlestat",
   "description": "集群状态：\n\n- Green  表示正常\n\n- Yellow 表示有复制shard不正常\n\n- Red      表示有主shard不正常",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "es_cluster_status{cluster='$Cluster'}",
     "metrics": [
      {
       "field": "status_code",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "singlestat",
   "description": "集群中节点数量",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "max(es_cluster_nodes_number)",
     "metrics": [
      {
       "field": "number_of_nodes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Data Nodes",
   "type": "singlestat",
   "description": "集群中数据节点数量",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "max(es_cluster_datanodes_number)",
     "metrics": [
      {
       "field": "number_of_nodes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Master Nodes",
   "type": "singlestat",
   "description": "集群中Master节点数量",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum(es_node_role_bool{role='master'})",
     "metrics": [
      {
       "field": "number_of_nodes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Indices",
   "type": "singlestat",
   "description": "集群中索引数量",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "count(count by (index) (es_index_status{cluster='$Cluster'}))",
     "metrics": [
      {
       "field": "indices.count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Documents",
   "type": "singlestat",
   "description": "集群中Primaries Shard中文档数量总和",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "avg(sum(es_index_doc_number{cluster='$Cluster',context='primaries'}) by (instance))",
     "metrics": [
      {
       "field": "indices.store.size_in_bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Active Shards",
   "type": "singlestat",
   "description": "集群中处于Active状态Shard数量",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "max(es_cluster_shards_number{type='active'})",
     "metrics": [
      {
       "field": "active_shards",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Unassigned Shards",
   "type": "singlestat",
   "description": "集群中尚未分配到节点的Shard数量",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "es_cluster_shards_number{cluster='$Cluster', type='unassigned'}",
     "metrics": [
      {
       "field": "unassigned_shards",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Initializing Shards",
   "type": "singlestat",
   "description": "集群中处于Initializing状态Shard数量",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum(es_cluster_shards_number{cluster='$Cluster', type='initializing'})",
     "metrics": [
      {
       "field": "initializing_shards",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Relocating Shards",
   "type": "singlestat",
   "description": "集群中重新分配节点Shard数量",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum(es_cluster_shards_number{cluster='$Cluster', type='relocating'})",
     "metrics": [
      {
       "field": "relocating_shards",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Tasks Max Waiting Seconds",
   "type": "singlestat",
   "description": "集群配置的任务最大等待时间，单位秒\n\n0表示没有最大等待时间限制",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "es_cluster_pending_tasks_number{cluster='$Cluster'}",
     "metrics": [
      {
       "field": "active_shards",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "singlestat",
   "description": "集群中待处理任务数量",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "es_cluster_task_max_waiting_time_seconds{cluster='$Cluster'}",
     "metrics": [
      {
       "field": "active_shards",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Node Overview",
   "type": "table",
   "description": "集群中所有节点信息概览",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "max(es_jvm_uptime_seconds{cluster='$Cluster'}) by (instance)"
    },
    {
     "expr": "max(es_os_cpu_percent{cluster='$Cluster'}) by (instance)"
    },
    {
     "expr": "es_jvm_mem_heap_used_bytes{cluster='$Cluster'} / es_jvm_mem_heap_max_bytes{cluster='$Cluster'} * 100"
    },
    {
     "expr": "100 - es_fs_total_free_bytes{cluster='$Cluster'} / es_fs_total_total_bytes{cluster='$Cluster'} * 100"
    },
    {
     "expr": "max(es_indices_doc_number{cluster='$Cluster'}) by (instance)"
    },
    {
     "expr": "max(es_indices_store_size_bytes{cluster='$Cluster'}) by (instance)"
    },
    {
     "expr": "max(es_node_role_bool{role='master'}) by (instance)"
    },
    {
     "expr": "max(es_node_role_bool{role='data'}) by (instance)"
    },
    {
     "expr": "max(es_node_role_bool{role='ingest'}) by (instance)"
    }
   ]
  },
  {
   "title": "Index Overview",
   "type": "table",
   "description": "集群中所有索引概览\n\nTODO: 去掉点开头index",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "avg(es_index_status{cluster='$Cluster', index!~'^[.].+'}) by (index)"
    },
    {
     "expr": "max(es_index_doc_number{cluster='$Cluster', index!~'^[.].+'}) by (index)"
    },
    {
     "expr": "avg(es_index_store_size_bytes{cluster='$Cluster',context='total', index!~'^[.].+'}) by (index)"
    },
    {
     "expr": "avg(es_index_store_size_bytes{cluster='$Cluster',context='primaries', index!~'^[.].+'}) by (index)"
    },
    {
     "expr": "max(es_index_shards_number{cluster='$Cluster', type='active', index!~'^[.].+'}) by (index)"
    },
    {
     "expr": "max(es_index_shards_number{cluster='$Cluster', type='unassigned', index!~'^[.].+'}) by (index)"
    }
   ]
  },
  {
   "title": "Node Indexing and Search Rate (/s)",
   "type": "graph",
   "description": "集群中所有节点速率，包括索引速率和搜索速率",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(es_indices_search_query_count{cluster='$Cluster'}[5m])) by (instance)",
     "legendFormat": "{{ instance }}.Search"
    },
    {
     "expr": "sum(rate(es_indices_indexing_index_count{cluster='$Cluster'}[5m])) by(instance)",
     "legendFormat": "{{ instance }}.Indexing"
    }
   ]
  },
  {
   "title": "Node Indexing and Search Latency",
   "type": "graph",
   "description": "集群中所有节点时延，包含索引时延和搜索时延",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "$nodename",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "1000 * sum(es_indices_indexing_index_time_seconds{cluster='$Cluster'} / es_indices_indexing_index_count{cluster='$Cluster'}) by (instance)",
     "legendFormat": "{{ instance }}.Indexing",
     "metrics": [
      {
       "field": "os.cpu.load_average.1m",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "os.cpu.load_average.5m",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    },
    {
     "expr": "1000 * sum(es_indices_search_query_time_seconds{cluster='$Cluster'} / es_indices_search_query_count{cluster='$Cluster'}) by (instance)",
     "legendFormat": "{{ instance }}.Search"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "graph",
   "description": "当前集群中所有节点CPU使用率",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "$nodename",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum(es_os_cpu_percent{cluster='$Cluster'}) by (instance)",
     "legendFormat": "{{ instance }}",
     "metrics": [
      {
       "field": "process.cpu.percent",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Node JVM Usage",
   "type": "graph",
   "description": "当前集群中所有节点JVM使用率",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "$nodename",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum(es_jvm_mem_heap_used_bytes{cluster='$Cluster'} / es_jvm_mem_heap_max_bytes{cluster='$Cluster'}) by (instance) * 100",
     "legendFormat": "{{ instance }}",
     "metrics": [
      {
       "field": "process.cpu.percent",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Node Storage Usage",
   "type": "graph",
   "description": "当前集群中所有节点根目录的磁盘使用率",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "$nodename",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "100 - sum(es_fs_total_free_bytes{cluster='$Cluster'} / es_fs_total_total_bytes{cluster='$Cluster'}) by (instance) * 100",
     "legendFormat": "{{ instance }}",
     "metrics": [
      {
       "field": "process.cpu.percent",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Node Data",
   "type": "graph",
   "description": "集群中所有节点索引文档磁盘占用量",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "$nodename",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum(es_indices_store_size_bytes{cluster='$Cluster'}) by (instance)",
     "legendFormat": "{{ instance }}",
     "metrics": [
      {
       "field": "os.mem.total_in_bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "os.mem.used_in_bytes",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Node Load",
   "type": "graph",
   "description": "当前集群中所有节点的负载，包括过去1分钟、5分钟、15分钟",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "$nodename",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum(es_os_load_average_one_minute{cluster='$Cluster'}) by (instance)",
     "legendFormat": "{{ instance }}.1m",
     "metrics": [
      {
       "field": "os.mem.total_in_bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "os.mem.used_in_bytes",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    },
    {
     "expr": "sum(es_os_load_average_five_minutes{cluster='$Cluster'}) by (instance)",
     "legendFormat": "{{ instance }}.5m"
    },
    {
     "expr": "sum(es_os_load_average_fifteen_minutes{cluster='$Cluster'}) by (instance)",
     "legendFormat": "{{ instance }}.15m"
    }
   ]
  },
  {
   "title": "Node Segment",
   "type": "graph",
   "description": "集群中所有节点Lucence Segment数量",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "$nodename",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum(es_indices_segments_number{cluster='$Cluster'}) by (instance)",
     "legendFormat": "{{ instance }}",
     "metrics": [
      {
       "field": "os.cpu.load_average.1m",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "os.cpu.load_average.5m",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Node Transport Rate(/s)",
   "type": "graph",
   "description": "集群中所有节点TCP数据收发速率",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-RX",
     "bucketAggs": [
      {
       "fake": true,
       "field": "$nodename",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum(rate(es_transport_tx_bytes_count{cluster='$Cluster'}[5m])) by (instance)",
     "legendFormat": "{{ instance }}.Send",
     "metrics": [
      {
       "field": "transport.rx_size_in_bytes",
       "hide": true,
       "id": "1",
       "inlineScript": "_value /60",
       "meta": {},
       "settings": { "script": { "inline": "_value /60" } },
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{$nodename}}-RX",
     "bucketAggs": [
      {
       "fake": true,
       "field": "$nodename",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum(rate(es_transport_rx_bytes_count{cluster='$Cluster'}[5m])) by (instance)",
     "legendFormat": "{{ instance }}.Recv",
     "metrics": [
      {
       "field": "transport.rx_size_in_bytes",
       "hide": true,
       "id": "1",
       "inlineScript": "_value /60",
       "meta": {},
       "settings": { "script": { "inline": "_value /60" } },
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Index", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Status",
   "type": "singlestat",
   "description": "索引状态：\n\n- Green  表示正常\n\n- Yellow 表示有复制shard不正常\n\n- Red      表示有主shard不正常",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 72 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "es_index_status{cluster='$Cluster', index='$Index'}"
    }
   ]
  },
  {
   "title": "Total Data",
   "type": "singlestat",
   "description": "索引文档占用磁盘空间",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 72 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "es_index_store_size_bytes{index='$Index', context='total'}"
    }
   ]
  },
  {
   "title": "Primaries Data",
   "type": "singlestat",
   "description": "索引中主分区文档占用磁盘空间",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 72 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "es_index_store_size_bytes{index='$Index', context='primaries'}"
    }
   ]
  },
  {
   "title": "Documents",
   "type": "singlestat",
   "description": "索引中文档数量",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 72 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "es_index_doc_number{cluster='$Cluster', index='$Index'}"
    }
   ]
  },
  {
   "title": "Total Shards",
   "type": "singlestat",
   "description": "索引中Shard数量",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 72 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "es_index_shards_number{cluster='$Cluster', index='$Index', type=\"active\"}"
    }
   ]
  },
  {
   "title": "Unassigned Shards",
   "type": "singlestat",
   "description": "索引中尚未分配到节点的Shard数量",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 72 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "es_index_shards_number{cluster='$Cluster', index='$Index', type=\"unassigned\"}"
    }
   ]
  },
  {
   "title": "Index Memory",
   "type": "graph",
   "description": "索引Lucence使用的堆内存使用量\n\n- Total：   总量\n- Terms：文本占用堆内存量\n- Points：数值占用堆内存量",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "$nodename",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "avg(es_index_segments_memory_bytes{cluster='$Cluster', index='$Index', context='total', type=\"all\"})",
     "legendFormat": "Lucence Total",
     "metrics": [
      {
       "field": "os.cpu.load_average.1m",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "os.cpu.load_average.5m",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{$nodename}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "$nodename",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "avg(es_index_segments_memory_bytes{cluster='$Cluster', index='$Index', context='total', type=\"terms\"})",
     "legendFormat": "Terms",
     "metrics": [
      {
       "field": "os.cpu.load_average.1m",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "os.cpu.load_average.5m",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    },
    {
     "expr": "avg(es_index_segments_memory_bytes{cluster='$Cluster', index='$Index', context='total', type=\"points\"})",
     "legendFormat": "Points"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "description": "索引占用磁盘空间\n\n- Total：        所有分区中文档占用磁盘空间\n- Primaries：主分区中文档占用磁盘空间",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "$nodename",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "avg(es_index_store_size_bytes{cluster='$Cluster', index='$Index', context='total'})",
     "legendFormat": "Store(Total)",
     "metrics": [
      {
       "field": "os.cpu.load_average.1m",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "os.cpu.load_average.5m",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{$nodename}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "$nodename",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "avg(es_index_store_size_bytes{cluster='$Cluster', index='$Index', context='primaries'})",
     "legendFormat": "Store(Primaries)",
     "metrics": [
      {
       "field": "os.cpu.load_average.1m",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "os.cpu.load_average.5m",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Search Rate (/s)",
   "type": "graph",
   "description": "索引搜索速率",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "$nodename",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "avg(rate(es_index_search_query_count{cluster='$Cluster', index='$Index', context='total'}[5m]))",
     "legendFormat": "Total",
     "metrics": [
      {
       "field": "os.cpu.load_average.1m",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "os.cpu.load_average.5m",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Indexing Rate(/s)",
   "type": "graph",
   "description": "索引索引文档速率\n\n- Total：索引中所有分区索引文档速率\n- Primaries： 索引中主分区索引文档速率",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "$nodename",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "avg(rate(es_index_indexing_index_count{cluster='$Cluster', index='$Index', context='total'}[1m]))",
     "legendFormat": "Total",
     "metrics": [
      {
       "field": "os.cpu.load_average.1m",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "os.cpu.load_average.5m",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    },
    {
     "expr": "avg(rate(es_index_indexing_index_count{cluster='$Cluster', index='$Index', context='primaries'}[1m]))",
     "legendFormat": "Primaries"
    }
   ]
  },
  {
   "title": "Segment Count",
   "type": "graph",
   "description": "索引Segment数量\n\n- Total：索引中所有分区占用Segment数量\n- Primaries：索引中主分区占用Segment数量",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "$nodename",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "avg(es_index_segments_number{cluster='$Cluster', index='$Index', context='total'})",
     "legendFormat": "Total",
     "metrics": [
      {
       "field": "os.cpu.load_average.1m",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "os.cpu.load_average.5m",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    },
    {
     "expr": "avg(es_index_segments_number{cluster='$Cluster', index='$Index', context='primaries'})",
     "legendFormat": "Primaries"
    }
   ]
  },
  {
   "title": "Document Count",
   "type": "graph",
   "description": "索引中主分区中文档数量",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "{{field}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "avg(es_index_doc_number{cluster='$Cluster',context='primaries', index='$Index'})",
     "legendFormat": "Document Count",
     "metrics": [
      {
       "field": "indices.docs.count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}