{
 "title": "Kafka Cluster Status",
 "description": "Kafka Cluster Status Dashboard",
 "tags": [ "Kafka" ],
 "time": { "from": "2020-08-21T19:27:19.736Z", "to": "2020-08-25T19:27:19.736Z" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(kafka_consumergroup_current_offset, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(kafka_consumergroup_current_offset{job=~\"$job\"}, instance)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_topic_partition_current_offset{instance='$instance',topic!='__consumer_offsets',topic!='--kafka'}, topic)"
   },
   {
    "name": "namespace",
    "label": "label_values(up{job=\"$job\"},namespace)",
    "query": "label_values(up{job=\"$job\"},namespace)"
   },
   {
    "name": "pod",
    "label": "label_values(up{job=\"$job\"},pod)",
    "query": "label_values(up{job=\"$job\"},pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Brokers",
     "type": "singlestat",
     "description": "集群中节点数量",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "avg(kafka_brokers)" }
     ]
    },
    {
     "title": "Partitions Per Topic",
     "type": "singlestat",
     "description": "集群中每个Topic包含Partition的数量",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "avg (kafka_topic_partitions{instance=\"$instance\",topic=~\"$topic\"})"
      }
     ]
    },
    {
     "title": "Lag by  Consumer Group",
     "type": "graph",
     "description": "消费组在指定topic中partition上的滞后量",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_consumergroup_lag{instance=\"$instance\",topic=~\"$topic\"}) by (consumergroup, topic, partition) ",
       "legendFormat": "{{consumergroup}} (topic: {{topic}}, partition: {{partition}})"
      }
     ]
    },
    {
     "title": "Message in(/min)",
     "type": "graph",
     "description": "Topic消息写入速率(/分钟）",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(kafka_topic_partition_current_offset{instance=~'$instance', topic=~\"$topic\"}[5m])/5) by (topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Message consume rate(/min)",
     "type": "graph",
     "description": "消费组在指定Topic上消息消费速率(/分钟）",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "sum(delta(kafka_consumergroup_current_offset{instance=~'$instance',topic=~\"$topic\"}[5m])/5) by (consumergroup, topic)",
       "legendFormat": "{{consumergroup}} (topic: {{topic}})"
      }
     ]
    }
   ]
  },
  { "title": "Resource Overhead", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Pod CPU Usage",
   "type": "graph",
   "description": "kafka实例的CPU使用情况，每一个点都是以过去5分钟为时间片来统计的，单位是Core",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (pod_name) (container_cpu_usage_seconds_total_irate5m_with_label{namespace=\"$namespace\",pod_name=~\"$pod\"})",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "avg by (pod_name) (kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\",pod_name=~\"$pod\"})",
     "legendFormat": "request"
    },
    {
     "expr": "avg by (pod_name) (kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\",pod_name=~\"$pod\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "graph",
   "description": "kafka实例的CPU使用情况，每一个点都是以过去5分钟为时间片来统计的，单位是Core",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (pod_name) (container_cpu_usage_seconds_total_irate5m_with_label{namespace=\"cpaas-system\",pod_name=~\"cpaas-kafka-.*\"})",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "avg by (pod_name) (kube_pod_container_resource_requests_cpu_cores{namespace=\"cpaas-system\",pod_name=~\"cpaas-kafka-.*\"})",
     "legendFormat": "request"
    },
    {
     "expr": "avg by (pod_name) (kube_pod_container_resource_limits_cpu_cores{namespace=\"cpaas-system\",pod_name=~\"cpaas-kafka-.*\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "graph",
   "description": "kafka实例的CPU使用情况，每一个点都是以过去5分钟为时间片来统计的，单位是Core",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (pod_name) (container_cpu_usage_seconds_total_irate5m_with_label{namespace=\"cpaas-system\",pod_name=~\"cpaas-kafka-.*\"})",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "avg by (pod_name) (kube_pod_container_resource_requests_cpu_cores{namespace=\"cpaas-system\",pod_name=~\"cpaas-kafka-.*\"})",
     "legendFormat": "request"
    },
    {
     "expr": "avg by (pod_name) (kube_pod_container_resource_limits_cpu_cores{namespace=\"cpaas-system\",pod_name=~\"cpaas-kafka-.*\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Filesystem Read Rate of Pod",
   "type": "graph",
   "description": "各个实例过去5分钟的平均读取磁盘的速率",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (rate(container_fs_reads_bytes_total{namespace=\"$namespace\", pod_name=~\"$pod\"}[5m]))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Filesystem Write Rate of Pod",
   "type": "graph",
   "description": "各个实例过去5分钟的平均写磁盘的速率",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (rate(container_fs_writes_bytes_total{namespace=\"$namespace\", pod_name=~\"$pod\"}[5m]))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  }
 ]
}