{
 "title": "Prometheus",
 "description": "Overview of metrics from Prometheus 2.0.  \r\nUseful for using prometheus to monitor your prometheus.\r\nRevisions welcome!",
 "tags": [ "promethues" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "query_result(prometheus_tsdb_head_samples_appended_total)"
   },
   {
    "name": "statefulset",
    "query": "query_result(kube_statefulset_labels)"
   }
  ]
 },
 "panels": [
  { "title": "Prometheus Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prometheus Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"})"
    }
   ]
  },
  {
   "title": "Samples Added per Second",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(prometheus_tsdb_head_samples_appended_total{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m]))"
    }
   ]
  },
  {
   "title": "Time Series",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"})"
    }
   ]
  },
  {
   "title": "Memory Chunks",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_chunks{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"})"
    }
   ]
  },
  {
   "title": "CPU Utilization of Pod",
   "type": "graph",
   "description": "Prometheus实例的CPU使用率",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (container_cpu_usage_seconds_total_irate5m{namespace=~\"$namespace\",pod_name=~\"$statefulset-[0-9]{1,3}\",image!=\"\",container_name!=\"POD\"}) / sum by (pod_name) (container_spec_cpu_quota{namespace=~\"$namespace\",pod_name=~\"$statefulset-[0-9]{1,3}\",image!=\"\",container_name!=\"POD\"}) * 100000",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Utilization of Pod",
   "type": "graph",
   "description": "Prometheus实例的内存使用率",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (container_memory_usage_bytes_without_cache{namespace=\"$namespace\",pod_name=~\"$statefulset-[0-9]{1,3}\"}) / sum by (pod_name) (container_spec_memory_limit_bytes{namespace=\"$namespace\",pod_name=~\"$statefulset-[0-9]{1,3}\",image!=\"\",container_name!=\"POD\"})",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Network Transmit Rate of Pod",
   "type": "graph",
   "description": "各个实例过去5分钟的平均网络发送速率",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (container_network_transmit_bytes_total_irate5m{namespace=\"$namespace\", pod_name=~\"$statefulset-[0-9]{1,3}\"})",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Network Received Rate of Pod",
   "type": "graph",
   "description": "各个实例过去5分钟的平均网络接收速率",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (container_network_receive_bytes_total_irate5m{namespace=\"$namespace\",pod_name=~\"$statefulset-[0-9]{1,3}\"})",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Filesystem Read Rate of Pod",
   "type": "graph",
   "description": "各个实例过去5分钟的平均读取磁盘的速率",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (rate(container_fs_reads_bytes_total{namespace=\"$namespace\", pod_name=~\"$statefulset-[0-9]{1,3}\"}[5m]))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Filesystem Write Rate of Pod",
   "type": "graph",
   "description": "各个实例过去5分钟的平均写磁盘的速率",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (rate(container_fs_writes_bytes_total{namespace=\"$namespace\", pod_name=~\"$statefulset-[0-9]{1,3}\"}[5m]))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  { "title": "Prometheus Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "HTTP Requests Average Latency Group by Handler",
   "type": "graph",
   "description": "过去5分钟内Prometheus示例的请求平均延迟的0.9分位，按照handler进行分组",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, avg(rate(prometheus_http_request_duration_seconds_bucket{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m])) by (handler, le))",
     "legendFormat": "Handler {{handler}}"
    }
   ]
  },
  {
   "title": "Prometheus Scrape Latency Group by Job and Service",
   "type": "graph",
   "description": "Prometheus当前抓取metrics的平均延迟，按照Job和Service进行分组",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(scrape_duration_seconds{}) by (job, service)",
     "legendFormat": "{{job}}/{{service}}"
    }
   ]
  },
  {
   "title": "Prometheus Engine Query Latency Group by Slice",
   "type": "graph",
   "description": "Prometheus引擎过去5分钟内在处理查询时的平均延时，会按照处理的阶段进行分组",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum (rate(prometheus_engine_query_duration_seconds_sum{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m])) by (slice)",
     "legendFormat": " Prometheus Engine {{slice}}"
    }
   ]
  },
  {
   "title": "Rule Evaluation Average Latency",
   "type": "graph",
   "description": "Prometheus在过去5分钟评估规则的平均延迟",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(prometheus_rule_evaluation_duration_seconds_sum{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m]) / rate(prometheus_rule_evaluation_duration_seconds_count{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m]))",
     "legendFormat": "Rule Evaluation Time"
    }
   ]
  },
  {
   "title": "Target Sync Latency Group by Job",
   "type": "graph",
   "description": "当前Prometheus过去5分钟内同步target的平均延迟，按照Job进行分组",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_target_sync_length_seconds_sum{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m])) by (scrape_job)",
     "legendFormat": "{{scrape_job}}"
    }
   ]
  },
  {
   "title": "Targets Discovered and Active",
   "type": "graph",
   "description": "当前Prometheus发现的目标数和当前正在抓取的目标数",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_sd_discovered_targets{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"})",
     "legendFormat": "Targets Discovered"
    },
    { "expr": "count(scrape_duration_seconds)", "legendFormat": "Target Active" }
   ]
  },
  {
   "title": "Targets UP Group by Service",
   "type": "graph",
   "description": "当前Prometheus采集的target是否UP，按照Service进行分组。如果正常可以采集对应的值是1，如果Service的全部实例都不能采集对应的值是0。",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (namespace, service) (up)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  { "title": "Prometheus Series", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Series Count",
   "type": "graph",
   "description": "当前Prometheus内存储的时序序列总和",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(prometheus_tsdb_head_series{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"})",
     "legendFormat": "Series Total"
    }
   ]
  },
  {
   "title": "Series Created and Removed",
   "type": "graph",
   "description": "Prometheus在过去5分钟内，创建/删除的时序序列数",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum( increase(prometheus_tsdb_head_series_created_total{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m]) )",
     "legendFormat": "Series created"
    },
    {
     "expr": "sum( increase(prometheus_tsdb_head_series_removed_total{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m]) )",
     "legendFormat": "Series removed"
    }
   ]
  },
  {
   "title": "Samples Append Rate",
   "type": "graph",
   "description": "Prometheus实例在过去5分钟添加时序序列采样点的总数",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_tsdb_head_samples_appended_total{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m]))",
     "legendFormat": "Samples Add Rate"
    }
   ]
  },
  {
   "title": "Head Chunks Count",
   "type": "graph",
   "description": "当前Prometheus的Head Chunks的数量",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_chunks{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"})",
     "legendFormat": "Head Chunks"
    }
   ]
  },
  {
   "title": "Rejected Scrapes Count",
   "type": "graph",
   "description": "Prometheus过去5分钟内拒绝的Scrape总数",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(prometheus_target_scrapes_exceeded_sample_limit_total{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m]))",
     "legendFormat": "Exceeded Sample Limit"
    },
    {
     "expr": "avg(rate(prometheus_target_scrapes_sample_duplicate_timestamp_total{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m]))",
     "legendFormat": "Duplicate Timestamp"
    },
    {
     "expr": "avg(rate(prometheus_target_scrapes_sample_out_of_bounds_total{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m]))",
     "legendFormat": "Out of Bounds"
    },
    {
     "expr": "avg(rate(prometheus_target_scrapes_sample_out_of_order_total{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m]))",
     "legendFormat": "Out of Order"
    }
   ]
  },
  {
   "title": "Prometheus Failures and Errors",
   "type": "graph",
   "description": "当前Prometheus过去5分钟内发生的失败和错误次数",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(net_conntrack_dialer_conn_failed_total{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m])) > 0",
     "legendFormat": "Failed Connections"
    },
    {
     "expr": "sum(increase(prometheus_evaluator_iterations_missed_total{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m])) > 0",
     "legendFormat": "Missed Iterations"
    },
    {
     "expr": "sum(increase(prometheus_evaluator_iterations_skipped_total{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m])) > 0",
     "legendFormat": "Skipped Iterations"
    },
    {
     "expr": "sum(increase(prometheus_rule_evaluation_failures_total{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m])) > 0",
     "legendFormat": "Evaluation"
    },
    {
     "expr": "sum(increase(prometheus_sd_azure_refresh_failures_total{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m])) > 0",
     "legendFormat": "Azure Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_consul_rpc_failures_total{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m])) > 0",
     "legendFormat": "Consul RPC"
    },
    {
     "expr": "sum(increase(prometheus_sd_dns_lookup_failures_total{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m])) > 0",
     "legendFormat": "DNS Lookup"
    },
    {
     "expr": "sum(increase(prometheus_sd_ec2_refresh_failures_total{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m])) > 0",
     "legendFormat": "EC2 Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_gce_refresh_failures_total{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m])) > 0",
     "legendFormat": "GCE Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_marathon_refresh_failures_total{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m])) > 0",
     "legendFormat": "Marathon Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_openstack_refresh_failures_total{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m])) > 0",
     "legendFormat": "Openstack Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_triton_refresh_failures_total{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m])) > 0",
     "legendFormat": "Triton Refresh"
    },
    {
     "expr": "sum(increase(prometheus_target_scrapes_exceeded_sample_limit_total{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m])) > 0",
     "legendFormat": "Sample Limit"
    },
    {
     "expr": "sum(increase(prometheus_target_scrapes_sample_duplicate_timestamp_total{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m])) > 0",
     "legendFormat": "Sample Duplicate Timestamp"
    },
    {
     "expr": "sum(increase(prometheus_target_scrapes_sample_out_of_bounds_total{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m])) > 0",
     "legendFormat": "Timestamp Out of Bounds"
    },
    {
     "expr": "sum(increase(prometheus_target_scrapes_sample_out_of_order_total{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m])) > 0",
     "legendFormat": "Sample Out of Order"
    },
    {
     "expr": "sum(increase(prometheus_treecache_zookeeper_failures_total{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m])) > 0",
     "legendFormat": "Zookeeper"
    },
    {
     "expr": "sum(increase(prometheus_tsdb_compactions_failed_total{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m])) > 0",
     "legendFormat": "TSDB Compactions"
    },
    {
     "expr": "sum(increase(prometheus_tsdb_head_series_not_found{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m])) > 0",
     "legendFormat": "Series Not Found"
    },
    {
     "expr": "sum(increase(prometheus_tsdb_reloads_failures_total{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m])) > 0",
     "legendFormat": "Reload"
    }
   ]
  },
  { "title": "Prometheus Inner", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Send Notifications Count",
   "type": "graph",
   "description": "当前Prometheus过去5分钟内发送的通知消息总数",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_notifications_sent_total{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m]))",
     "legendFormat": "Notifications Sent Count"
    }
   ]
  },
  {
   "title": "Successful Config Reload",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(prometheus_config_last_reload_successful{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"})",
     "legendFormat": "Reload Success"
    }
   ]
  },
  {
   "title": "Scrape Interval Group by Interval and Quantile",
   "type": "graph",
   "description": "当前Prometheus从目标抓取metrics的间隔分布情况",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(prometheus_target_interval_length_seconds{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}) by (quantile, interval)",
     "legendFormat": "Scrape Interval {{interval}}/{{quantile}} "
    }
   ]
  },
  {
   "title": "Target Scrape Count Group by Interval",
   "type": "graph",
   "description": "当前Prometheus过去5分钟内抓取目标的次数，按照时间间隔进行分组",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg (increase(prometheus_target_interval_length_seconds_count{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m])) by (interval)",
     "legendFormat": "Scrape Count {{interval}}"
    }
   ]
  },
  {
   "title": "Goroutines Group by Instance",
   "type": "graph",
   "description": "Prometheus实例的goroutines数量",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (pod) (go_goroutines{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"})",
     "legendFormat": "{{pod}}/goroutines"
    }
   ]
  },
  {
   "title": "GC Durations Group by Instance",
   "type": "graph",
   "description": "过去5分钟内Prometheus花在GC上的时间，按照实例进行分组",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (pod) (increase(go_gc_duration_seconds_sum{namespace=~\"$namespace\",pod=~\"$statefulset-[0-9]{1,3}\"}[5m]))",
     "legendFormat": "{{pod}}/gc_durations"
    }
   ]
  }
 ]
}