{
 "title": "Zookeerper Cluster Status",
 "description": "Zookeerper Cluster Status Dashboard",
 "tags": [ "zookeeper" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": "label_values(zookeeper_exporter_build_info, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "singlestat",
   "description": "集群状态\n\n- Green：正常\n- Red： 异常\n\n注：只要有一个节点不正常，集群状态就是Red",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "1 - min(zk_up)" }
   ]
  },
  {
   "title": "ZNode Count",
   "type": "singlestat",
   "description": "ZNode数量",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "last_time",
   "targets": [
    { "expr": "zk_znode_count" }
   ]
  },
  {
   "title": "Watch Count",
   "type": "singlestat",
   "description": "集群Watch数量",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    { "expr": "sum(zk_watch_count)" }
   ]
  },
  {
   "title": "Synced Followers",
   "type": "singlestat",
   "description": "已同步从节点数量",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "last_time",
   "targets": [
    { "expr": "zk_synced_followers" }
   ]
  },
  {
   "title": "Pending Sync",
   "type": "singlestat",
   "description": "阻塞中的sync操作数量",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "last_time",
   "targets": [
    { "expr": "zk_pending_syncs" }
   ]
  },
  {
   "title": "Approximate Data",
   "type": "singlestat",
   "description": "近似数据总和大小",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "expr": "zk_approximate_data_size" }
   ]
  },
  {
   "title": "Znode Count",
   "type": "graph",
   "description": "集群ZNode数量",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "max(zk_znode_count)", "legendFormat": "ZNode Count" }
   ]
  },
  {
   "title": "Watch Count",
   "type": "graph",
   "description": "集群Watch数量",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(zk_watch_count)", "legendFormat": "Watch Count" }
   ]
  },
  {
   "title": "Alive Connections",
   "type": "graph",
   "description": "集群活跃连接数",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "sum(zk_num_alive_connections)", "legendFormat": "Conn" }
   ]
  },
  {
   "title": "Packages Rate(/s)",
   "type": "graph",
   "description": "集群收发包速率",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "sum(rate(zk_packets_sent[5m]))", "legendFormat": "Send" },
    {
     "expr": "sum(rate(zk_packets_received[5m]))",
     "legendFormat": "Recv"
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Status",
   "type": "singlestat",
   "description": "节点状态\n\n- Online：节点在线\n- Offline： 节点离线",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - zk_up{instance='$Instance'}"
    }
   ]
  },
  {
   "title": "Role",
   "type": "singlestat",
   "description": "节点角色\n\n- leader：主节点\n- follower： 从节点",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 19 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "zk_server_state{instance='$Instance'}"
    }
   ]
  },
  {
   "title": "Watch Count",
   "type": "singlestat",
   "description": "集群Watch数量",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 19 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "zk_watch_count{instance='$Instance'}"
    }
   ]
  },
  {
   "title": "Alive Connctions",
   "type": "singlestat",
   "description": "活跃连接数",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 19 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "zk_num_alive_connections{instance='$Instance'}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "singlestat",
   "description": "节点打开文件描述符数量",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 19 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "zk_open_file_descriptor_count{instance='$Instance'}"
    }
   ]
  },
  {
   "title": "Max File Descriptors",
   "type": "singlestat",
   "description": "节点最大文件描述符数量",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 19 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "zk_max_file_descriptor_count{instance='$Instance'}"
    }
   ]
  },
  {
   "title": "Watch count",
   "type": "graph",
   "description": "Watch数量",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "zk_watch_count{instance='$Instance'}",
     "legendFormat": "Watch Count"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "description": "时延",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "zk_avg_latency{instance='$Instance'}",
     "legendFormat": "Avg"
    },
    {
     "expr": "zk_min_latency{instance='$Instance'}",
     "legendFormat": "Min"
    },
    {
     "expr": "zk_max_latency{instance='$Instance'}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Outstanding Requests",
   "type": "graph",
   "description": "堆积请求数量",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "zk_outstanding_requests{instance='$Instance'}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Packages Rate(/s)",
   "type": "graph",
   "description": "包发送接收速率",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "rate(zk_packets_received{instance='$Instance'}[5m])",
     "legendFormat": "Send"
    },
    {
     "expr": "rate(zk_packets_sent{instance='$Instance'}[5m])",
     "legendFormat": "Recv"
    }
   ]
  }
 ]
}