{
 "title": "Asm-docs",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_labels{label_service_name=\"$component\"},namespace)"
   },
   { "name": "component", "label": "Component", "query": "asm-docs" },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_labels{namespace=\"$namespace\",label_service_name=\"$component\"},pod)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h2>Component $component</h2></center>"
  },
  { "title": "Health of $component", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Component Status",
   "type": "singlestat",
   "description": "组件的健康状态(Pod Running/Pod 副本数)",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 4 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum (kube_pod_status_phase{namespace=~\"$namespace\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\", phase=\"Running\"}==1))/(sum (kube_pod_status_phase{namespace=~\"$namespace\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"}==1))"
    }
   ]
  },
  {
   "title": "Pod Total",
   "type": "singlestat",
   "description": "组件中所有Pod的总数",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count (kube_pod_info_with_label{namespace=\"$namespace\",label_service_name=\"$component\"})"
    }
   ]
  },
  {
   "title": "Pod Abnormal",
   "type": "singlestat",
   "description": "异常Pod的数量",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_info_with_label{namespace=\"$namespace\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\",phase!=\"Running\"}) or on() vector(0)"
    }
   ]
  },
  {
   "title": "Pod Info",
   "type": "table",
   "description": "组件中所有Pod的详细信息及状态",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "kube_pod_info_with_label{namespace=\"$namespace\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"}"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "graph",
   "description": "组件中所有Pod的状态",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kube_deployment_spec_replicas{namespace=\"$namespace\",deployment=~\"$component\"})",
     "legendFormat": "Replicas"
    },
    {
     "expr": "sum (kube_pod_status_phase{namespace=\"$namespace\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\",phase=\"Running\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum (kube_pod_status_phase{namespace=\"$namespace\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\",phase!=\"Running\"})",
     "legendFormat": "Not Running"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "graph",
   "description": "组件中Pod的重启情况",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (kube_pod_container_status_restarts_total{namespace=\"$namespace\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Usage of $component", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU Utilization",
   "type": "singlestat",
   "description": "组件CPU的真实使用率(实际使用量/Limit)",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (deployment_name) (container_cpu_usage_seconds_total_irate5m{namespace=\"$namespace\",pod_name=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\",image!=\"\",container_name!=\"POD\"}) / sum by (deployment_name) (container_spec_cpu_quota{namespace=\"$namespace\",pod_name=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\",image!=\"\",container_name!=\"POD\"}) * 100000"
    }
   ]
  },
  {
   "title": "CPU Limits",
   "type": "singlestat",
   "description": "组件的CPU Limits",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"})  / count(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"})"
    }
   ]
  },
  {
   "title": "CPU Requests",
   "type": "singlestat",
   "description": "组件的CPU Requests",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"}) / count(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"})"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "singlestat",
   "description": "组件内存的真实使用率(实际使用量/Limit)",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 18 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (deployment_name) (container_memory_usage_bytes_without_cache{namespace=\"$namespace\",pod_name=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"}) / sum by (deployment_name) (container_spec_memory_limit_bytes{namespace=\"$namespace\",pod_name=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\",image!=\"\",container_name!=\"POD\"})",
     "legendFormat": "pod_restart_count"
    }
   ]
  },
  {
   "title": "Memory Limits",
   "type": "singlestat",
   "description": "组件的内存Limits",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 18 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"}) / count(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"})"
    }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "singlestat",
   "description": "组件的内存Requests",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 18 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"}) / count(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"})"
    }
   ]
  },
  {
   "title": "CPU Utilization of Pod",
   "type": "graph",
   "description": "组件中各Pod的CPU利用率",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (container_cpu_usage_seconds_total_irate5m{namespace=\"$namespace\",pod_name=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\",image!=\"\",container_name!=\"POD\"}) / sum by (pod_name) (container_spec_cpu_quota{namespace=\"$namespace\",pod_name=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\",image!=\"\",container_name!=\"POD\"}) * 100000",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Utilization of Pod",
   "type": "graph",
   "description": "组件中各Pod的内存利用率",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (container_memory_usage_bytes_without_cache{namespace=\"$namespace\",pod_name=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"}) / sum by (pod_name) (container_spec_memory_limit_bytes{namespace=\"$namespace\",pod_name=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\",image!=\"\",container_name!=\"POD\"})",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Network Transmit Rate of Pod",
   "type": "graph",
   "description": "组件中各Pod的网络发送速率",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (container_network_transmit_bytes_total_irate5m{namespace=\"$namespace\", pod_name=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"})",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Network Receive Rate of Pod",
   "type": "graph",
   "description": "组件中各Pod的网络接收速率",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (container_network_receive_bytes_total_irate5m{namespace=\"$namespace\",pod_name=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"})",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "API Status of $component",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Requests Count Group by Code",
     "type": "graph",
     "description": "过去5分钟内，组件所有API请求的返回结果，按照 2xx、4xx、5xx状态分类",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (delta(requests_total_by_pod_method_code_handler_endpoint{code=~\"2.*\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"}[5m]))",
       "legendFormat": "Success"
      },
      {
       "expr": "sum (delta(requests_total_by_pod_method_code_handler_endpoint{code=~\"4.*\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"}[5m]))",
       "legendFormat": "Client Error"
      },
      {
       "expr": "sum (delta(requests_total_by_pod_method_code_handler_endpoint{code=~\"5.*\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"}[5m]))",
       "legendFormat": "Server Error"
      }
     ]
    },
    {
     "title": "Client Error Count Group by Method and  Handler",
     "type": "graph",
     "description": "过去5分钟内，组件所有API返回状态码是 4xx的统计，按照请求方法和接口分类",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(method,handler,code) (delta(requests_total_by_pod_method_code_handler_endpoint{code=~\"4..\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"}[5m]))",
       "legendFormat": "{{method}} {{handler}} {{code}}"
      }
     ]
    },
    {
     "title": "Server Error Count Group by Method and Handler",
     "type": "graph",
     "description": "过去5分钟内，组件所有API返回状态码是5xx的统计，按照请求方法和接口分类",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": " sum by(method,handler,code) (delta(requests_total_by_pod_method_code_handler_endpoint{code=~\"5..\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"}[5m]))",
       "legendFormat": "{{method}} {{handler}} {{code}}"
      }
     ]
    },
    {
     "title": "API Requests Latency Group by Pod and Quantile",
     "type": "graph",
     "description": "组件中每个Pod的请求延迟统计，分别展示分位数0.5、0.9、0.99的数据",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "{job=\"$component\",__name__=~\".*request_duration_seconds\"}",
       "legendFormat": "{{pod}}/{{quantile}}"
      }
     ]
    },
    {
     "title": "API Requests Average Latency Group by Pod",
     "type": "graph",
     "description": "过去5分钟内，组件中每个Pod的平均延迟",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "delta({job=\"$component\",__name__=~\".*request_duration_seconds_sum\"}[5m]) / delta({job=\"$component\",__name__=~\".*request_duration_seconds_count\"}[5m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "API Requests Count Top5 Group by Method and Handler",
     "type": "graph",
     "description": "过去5分钟内，组件请求数量最多的5个API，按照请求方法和接口分类",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5, sum by(method,handler) (increase(requests_total_by_pod_method_code_handler_endpoint{pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"}[5m])))",
       "legendFormat": "{{method}} {{handler}}"
      }
     ]
    },
    {
     "title": "API Requests Rate Group by Method and Handler",
     "type": "graph",
     "description": "过去5分钟内，组件的API请求速率(次/分钟)，按照请求方法和接口分类",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(handler,method) (rate(requests_total_by_pod_method_code_handler_endpoint{pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"}[5m])) * 60",
       "legendFormat": "{{method}} {{handler}}"
      }
     ]
    }
   ]
  }
 ]
}