{
 "title": "Devops-controller",
 "tags": [ "controller" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_labels{label_service_name=\"$component\"},namespace)"
   },
   { "name": "component", "label": "Component", "query": "devops-controller" },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_labels{namespace=\"$namespace\",label_service_name=\"$component\"},pod)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h2>Component $component</h2></center>"
  },
  { "title": "Health of $component", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Component Status",
   "type": "singlestat",
   "description": "组件的健康状态(Pod Running/Pod 副本数)",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 4 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum (kube_pod_status_phase{namespace=~\"$namespace\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\", phase=\"Running\"}==1))/(sum (kube_pod_status_phase{namespace=~\"$namespace\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"}==1))"
    }
   ]
  },
  {
   "title": "Pod Total",
   "type": "singlestat",
   "description": "组件中所有Pod的总数",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count (kube_pod_info_with_label{namespace=\"$namespace\",label_service_name=\"$component\"})"
    }
   ]
  },
  {
   "title": "Pod Abnormal",
   "type": "singlestat",
   "description": "异常Pod的数量",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_info_with_label{namespace=\"$namespace\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\",phase!=\"Running\"}) or on() vector(0)"
    }
   ]
  },
  {
   "title": "Pod Info",
   "type": "table",
   "description": "组件中所有Pod的详细信息及状态",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "kube_pod_info_with_label{namespace=\"$namespace\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"}"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "graph",
   "description": "组件中所有Pod的状态",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kube_deployment_spec_replicas{namespace=\"$namespace\",deployment=~\"$component\"})",
     "legendFormat": "Replicas"
    },
    {
     "expr": "sum (kube_pod_status_phase{namespace=\"$namespace\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\", phase=\"Running\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum (kube_pod_status_phase{namespace=\"$namespace\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\", phase!=\"Running\"})",
     "legendFormat": "Not Running"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "graph",
   "description": "组件中Pod的重启情况",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (kube_pod_container_status_restarts_total{namespace=\"$namespace\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "singlestat",
   "description": "组件CPU的真实使用率(实际使用量/Limit)",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 17 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (deployment_name) (container_cpu_usage_seconds_total_irate5m{namespace=\"$namespace\",pod_name=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\",image!=\"\",container_name!=\"POD\"}) / sum by (deployment_name) (container_spec_cpu_quota{namespace=\"$namespace\",pod_name=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\",image!=\"\",container_name!=\"POD\"}) * 100000"
    }
   ]
  },
  {
   "title": "CPU Limits",
   "type": "singlestat",
   "description": "组件的CPU Limits",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 17 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"})  / count(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"})"
    }
   ]
  },
  {
   "title": "CPU Requests",
   "type": "singlestat",
   "description": "组件的CPU Requests",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 17 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"}) / count(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"})"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "singlestat",
   "description": "组件内存的真实使用率(实际使用量/Limit)",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 17 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (deployment_name) (container_memory_usage_bytes_without_cache{namespace=\"$namespace\",pod_name=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"}) / sum by (deployment_name) (container_spec_memory_limit_bytes{namespace=\"$namespace\",pod_name=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\",image!=\"\",container_name!=\"POD\"})",
     "legendFormat": "pod_restart_count"
    }
   ]
  },
  {
   "title": "Memory Limits",
   "type": "singlestat",
   "description": "组件的内存Limits",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 17 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"}) / count(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"})"
    }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "singlestat",
   "description": "组件的内存Requests",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 17 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"}) / count(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"})"
    }
   ]
  },
  {
   "title": "Usage of $component",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization of Pod",
     "type": "graph",
     "description": "组件中各Pod的CPU利用率",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (pod_name) (container_cpu_usage_seconds_total_irate5m{namespace=\"$namespace\",pod_name=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\",image!=\"\",container_name!=\"POD\"}) / sum by (pod_name) (container_spec_cpu_quota{namespace=\"$namespace\",pod_name=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\",image!=\"\",container_name!=\"POD\"}) * 100000",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Memory Utilization of Pod",
     "type": "graph",
     "description": "组件中各Pod的内存利用率",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (pod_name) (container_memory_usage_bytes_without_cache{namespace=\"$namespace\",pod_name=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"}) / sum by (pod_name) (container_spec_memory_limit_bytes{namespace=\"$namespace\",pod_name=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\",image!=\"\",container_name!=\"POD\"})",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Network Transmit Rate of Pod",
     "type": "graph",
     "description": "组件中各Pod的网络发送速率",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by (pod_name) (container_network_transmit_bytes_total_irate5m{namespace=\"$namespace\", pod_name=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"})",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Network Receive Rate of Pod",
     "type": "graph",
     "description": "组件中各Pod的网络接收速率",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by (pod_name) (container_network_receive_bytes_total_irate5m{namespace=\"$namespace\",pod_name=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"})",
       "legendFormat": "{{pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Controller Status of $component",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Work Queue Add Count",
     "type": "graph",
     "description": "过去5分钟内，Controller的工作队列增加了多少消息",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(controller_runtime_reconcile_total{job=\"$component\"}[5m])) by (job, controller)",
       "legendFormat": "{{job}}.{{controller}} "
      }
     ]
    },
    {
     "title": "Work Queue Average Latency Histogram",
     "type": "graph",
     "description": "过去5分钟内，Controller处理队列消息耗费的时间的分布状况，比如0.99的曲线在t时刻对应的值是3s，就表示99%的消息耗时在3s以内。",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, avg by (job, controller, le) (rate(controller_runtime_reconcile_time_seconds_bucket{job=\"$component\"}[5m])))",
       "legendFormat": "{{job}}.{{controller}} 0.99"
      },
      {
       "expr": "histogram_quantile(0.9, avg by (job, controller, le) (rate(controller_runtime_reconcile_time_seconds_bucket{job=\"$component\"}[5m])))",
       "legendFormat": "{{job}}.{{controller}} 0.9"
      },
      {
       "expr": "histogram_quantile(0.5, avg by (job, controller, le) (rate(controller_runtime_reconcile_time_seconds_bucket{job=\"$component\"}[5m])))",
       "legendFormat": "{{job}}.{{controller}} 0.5"
      }
     ]
    },
    {
     "title": "Work Queue Depth",
     "type": "graph",
     "description": "当前Controller要处理的工作队列深度",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(workqueue_depth{job=\"$component\"}) by (job, name)",
       "legendFormat": "{{job}}.{{name}}"
      }
     ]
    },
    {
     "title": "Work Queue Average Latency Histogram (Corrected)",
     "type": "graph",
     "description": "过去5分钟内，Controller处理队列消息耗费的时间的分布状况，比如0.99的曲线在t时刻对应的值是3s，就表示99%的消息耗时在3s以内。",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, avg by (job, kind, le) (rate(controller_runtime_reconcile_correction_time_seconds_bucket{job=\"$component\"}[5m])))",
       "legendFormat": "{{job}}.{{kind}} 0.99"
      },
      {
       "expr": "histogram_quantile(0.9, avg by (job, kind, le) (rate(controller_runtime_reconcile_correction_time_seconds_bucket{job=\"$component\"}[5m])))",
       "legendFormat": "{{job}}.{{kind}} 0.9"
      },
      {
       "expr": "histogram_quantile(0.5, avg by (job, kind, le) (rate(controller_runtime_reconcile_correction_time_seconds_bucket{job=\"$component\"}[5m])))",
       "legendFormat": "{{job}}.{{kind}} 0.5"
      }
     ]
    },
    {
     "title": "Controller Goroutines",
     "type": "graph",
     "description": "当前Controller内的Goroutines数量",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{job=\"$component\"}",
       "legendFormat": "{{pod}}.goroutines"
      }
     ]
    },
    {
     "title": "Resource Reconcile Latency",
     "type": "graph",
     "description": "不同的资源的同步所需的耗时",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg by (job, kind, name) (resource_reconcile_time_seconds)",
       "legendFormat": "{{kind}}/{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "API Status of $component",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Controller Webhook Requests Latency",
     "type": "graph",
     "description": "过去5分钟内，Controller处理Webhook请求的平均延迟[invalid]：未筛选出数据",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(controller_runtime_webhook_latency_seconds_bucket{job=\"$component\"}[5m])) by (job, le))",
       "legendFormat": "Average Webhook Latency"
      }
     ]
    },
    {
     "title": "Controller Webhook Requests Count",
     "type": "graph",
     "description": "过去5分钟内，Controller处理Webhook请求结果数，按照允许和阻止分为两类[invalid]：未筛选出数据",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (succeeded) (delta(controller_runtime_webhook_requests_total{job=\"$component\", succeeded=\"true\"}[5m]))",
       "legendFormat": "Allowed Requests"
      },
      {
       "expr": "sum by (succeeded) (delta(controller_runtime_webhook_requests_total{job=\"$component\", succeeded=\"false\"}[5m]))",
       "legendFormat": "Rejected Requests"
      }
     ]
    },
    {
     "title": "Controller Webhook Requests Latency Group by Webhook",
     "type": "graph",
     "description": "过去5分钟内，Controller处理Webhook请求的平均延迟，按照Webhook的名称进行分组[invalid]：未筛选出数据",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, avg by (webhook, le)(rate(controller_runtime_webhook_latency_seconds_bucket{job=\"$component\"}[5m])))",
       "legendFormat": "{{webhook}} Latency"
      }
     ]
    },
    {
     "title": "Controller Webhook Requests Count Group by Webhook",
     "type": "graph",
     "description": "过去5分钟内，Controller处理Webhook请求结果数，按照允许和阻止分为两类[invalid]：未筛选出数据",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (webhook, succeeded) (delta(controller_runtime_webhook_latency_seconds_sum{job=\"$component\", succeeded=\"true\"}[5m]))",
       "legendFormat": "{{webhook}} Allowed "
      },
      {
       "expr": "sum by (webhook, succeeded) (delta(controller_runtime_webhook_requests_total{job=\"$component\", succeeded=\"false\"}[5m]))",
       "legendFormat": "{{webhook}} Rejected"
      }
     ]
    },
    {
     "title": "Rest Client Requests Latency Group by Pod",
     "type": "graph",
     "description": "过去5分钟内，按照Pod进行分组来计算Controller组件发出的Rest API请求的平均延迟",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(rest_client_request_latency_seconds_bucket{job=\"$component\"}[5m])) by (pod,le))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Rest Client Requests Latency Group by Verb and URL",
     "type": "graph",
     "description": "过去5分钟内，按照Verb和URL进行分组来计算Controller发出的Rest API请求的平均延迟",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, avg(rate(rest_client_request_latency_seconds_bucket{job=\"$component\"}[5m])) by (url,verb,le))",
       "legendFormat": "{{verb}} {{url}}"
      }
     ]
    },
    {
     "title": "Rest Client Requests Rate Group by Verb and URL",
     "type": "graph",
     "description": "过去5分钟内，按照URL和Verb进行分组来计算Controller发出Rest API请求的速率",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (url,verb) (delta(rest_client_request_latency_seconds_count{job=\"$component\"}[5m]))",
       "legendFormat": "{{verb}} {{url}}"
      }
     ]
    },
    {
     "title": "Rest Client Requests Count Group by Response Code",
     "type": "graph",
     "description": "过去5分钟内Controller发出所有Rest API请求数，按照返回状态码2XX/4XX/5XX进行分组统计",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(rest_client_requests_total{code=~\"2.*\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"}[5m]))",
       "legendFormat": "Requests 2XX"
      },
      {
       "expr": "sum(delta(rest_client_requests_total{code=~\"4.*\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"}[5m]))",
       "legendFormat": "Requests 4XX"
      },
      {
       "expr": "sum(delta(rest_client_requests_total{code=~\"5.*\",pod=~\"$pod-[a-z0-9]{7,10}-[a-z0-9]{5}\"}[5m]))",
       "legendFormat": "Requests 5XX"
      }
     ]
    }
   ]
  }
 ]
}