{
 "title": "Kube-OVN / Pinger",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "OVS Up",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    { "expr": "sum(pinger_ovs_up)" }
   ]
  },
  {
   "title": "OVS Down",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(pinger_ovs_down)" }
   ]
  },
  {
   "title": "OVN-Controller Up",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(pinger_ovn_controller_up)" }
   ]
  },
  {
   "title": "OVN-Controller Down",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(pinger_ovn_controller_down)"
    }
   ]
  },
  {
   "title": "DNS Accessible",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(pinger_dns_healthy)" }
   ]
  },
  {
   "title": "DNS Unaccessible",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(pinger_dns_unhealthy)" }
   ]
  },
  {
   "title": "APIServer Accessible",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(pinger_apiserver_healthy)" }
   ]
  },
  {
   "title": "APIServer Unaccessible",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(pinger_apiserver_unhealthy)"
    }
   ]
  },
  {
   "title": "ApiServer Latency Avg.",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(sum(delta(pinger_apiserver_latency_ms_sum[10m])) by (nodeName))/(sum(delta(pinger_apiserver_latency_ms_count[10m])) by (nodeName))",
     "legendFormat": "{{nodeName}}"
    }
   ]
  },
  {
   "title": "DNS Latency Avg.",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(sum(delta(pinger_dns_latency_ms_sum[10m])) by (nodeName))/(sum(delta(pinger_dns_latency_ms_count[10m])) by (nodeName))",
     "legendFormat": "{{nodeName}}"
    }
   ]
  },
  {
   "title": "Ping Pod Failure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(pinger_pod_ping_lost_total[5m])) by (src_node_name)",
     "legendFormat": "src-{{src_node_name}}"
    },
    {
     "expr": "sum(delta(pinger_pod_ping_lost_total[5m])) by (target_node_name)",
     "legendFormat": "target-{{target_node_name}}"
    }
   ]
  },
  {
   "title": "Ping Node Failure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(pinger_node_ping_lost_total[5m])) by (src_node_name)",
     "legendFormat": "src-{{src_node_name}}"
    },
    {
     "expr": "sum(delta(pinger_node_ping_lost_total[5m])) by (target_node_name)",
     "legendFormat": "target-{{target_node_name}}"
    }
   ]
  }
 ]
}