{
 "title": "Platform Component Overview",
 "tags": [ "overview" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_labels{label_service_name!=\"\"},namespace)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h2>Platform Component Overview</h2></center>"
  },
  {
   "title": "Component Total",
   "type": "singlestat",
   "description": "所有组件的总数",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by(label_service_name) (kube_pod_info_with_label{label_service_name!=\"\"}))"
    }
   ]
  },
  {
   "title": "Component Abnormal",
   "type": "singlestat",
   "description": "异常组件的总数",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by(label_service_name) (kube_pod_info_with_label{label_service_name!=\"\",phase!=\"Running\"})) or on() vector(0)"
    }
   ]
  },
  {
   "title": "Pod Total",
   "type": "singlestat",
   "description": "所有组件Pod的总数",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count (kube_pod_info_with_label{label_service_name!=\"\"})"
    }
   ]
  },
  {
   "title": "Pod Abnormal",
   "type": "singlestat",
   "description": "异常Pod的数量",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by(pod) (kube_pod_info_with_label{label_service_name!=\"\",phase!=\"Running\",phase!=\"Succeeded\"})) or on() vector(0)"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "singlestat",
   "description": "所有组件CPU请求值在集群中的占用情况",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests_cpu_cores{node!=\"\"} * on(pod, namespace) group_left(phase) (kube_pod_status_phase{phase!=\"Failed\",phase!=\"Succeeded\"} == 1) * on(namespace, pod) group_left(label_service_name) (kube_pod_info_with_label{namespace=~\".*\",pod=~\".*\",label_service_name!=\"\"}))  / sum(kube_node_status_allocatable_cpu_cores)"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "singlestat",
   "description": "所有组件内存请求值在集群中的占用情况",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests_memory_bytes{node!=\"\"} * on(pod, namespace) group_left(phase) (kube_pod_status_phase{phase!=\"Failed\",phase!=\"Succeeded\"} == 1) * on(namespace, pod) group_left(label_service_name) (kube_pod_info_with_label{namespace=~\".*\",pod=~\".*\",label_service_name!=\"\"}))  / sum(kube_node_status_allocatable_memory_bytes)"
    }
   ]
  },
  {
   "title": "Component Info",
   "type": "table",
   "description": "所有组件的详细信息和状态",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "count by(label_service_name,namespace) (count by(label_service_name,phase,namespace) (kube_pod_info_with_label{label_service_name!=\"\"}))"
    }
   ]
  },
  {
   "title": "Abnormal Pods",
   "type": "table",
   "description": "异常Pod的详细信息[invalid]：未筛选出数据",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "kube_pod_info_with_label{phase!=\"Running\",phase!=\"Succeeded\",label_service_name!=\"\"}"
    }
   ]
  },
  {
   "title": "CPU Utilization of component",
   "type": "graph",
   "description": "各组件的CPU使用率",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(label_service_name) (container_cpu_usage_seconds_total_irate5m_with_label{label_service_name!=\"\",pod_name=~\".*\",image!=\"\",container_name!=\"POD\"}) / sum by(label_service_name) (container_spec_cpu_quota_with_label{label_service_name!=\"\",pod_name=~\".*\",image!=\"\",container_name!=\"POD\"}) * 100000",
     "legendFormat": "{{label_service_name}}"
    }
   ]
  },
  {
   "title": "Memory Utilization of component",
   "type": "graph",
   "description": "各组件的内存使用率",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(label_service_name) (container_memory_usage_bytes_without_cache_with_label{label_service_name!=\"\",namespace=\"$namespace\",pod_name=~\".*\"}) / sum by (label_service_name) (container_spec_memory_limit_bytes_with_label{namespace=\"$namespace\",pod_name=~\".*\",image!=\"\",container_name!=\"POD\",label_service_name!=\"\"})",
     "legendFormat": "{{label_service_name}}"
    }
   ]
  },
  {
   "title": "CPU Limits",
   "type": "singlestat",
   "description": "所有组件的CPU Limit总和",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 21 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_limits_cpu_cores{node!=\"\"} * on(pod, namespace) group_left(phase) (kube_pod_status_phase{phase!=\"Failed\",phase!=\"Succeeded\"} == 1) * on(namespace, pod) group_left(label_service_name) (kube_pod_info_with_label{namespace=~\".*\",pod=~\".*\",label_service_name!=\"\"}))"
    }
   ]
  },
  {
   "title": "CPU Requests",
   "type": "singlestat",
   "description": "所有组件的CPU Request总和",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 21 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests_cpu_cores{node!=\"\"} * on(pod, namespace) group_left(phase) (kube_pod_status_phase{phase!=\"Failed\",phase!=\"Succeeded\"} == 1) * on(namespace, pod) group_left(label_service_name) (kube_pod_info_with_label{namespace=~\".*\",pod=~\".*\",label_service_name!=\"\"}))"
    }
   ]
  },
  {
   "title": "Memory Limits",
   "type": "singlestat",
   "description": "所有组件的内存Limit总和",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 21 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_limits_memory_bytes{node!=\"\"} * on(pod, namespace) group_left(phase) (kube_pod_status_phase{phase!=\"Failed\",phase!=\"Succeeded\"} == 1) * on(namespace, pod) group_left(label_service_name) (kube_pod_info_with_label{namespace=~\".*\",pod=~\".*\",label_service_name!=\"\"}))"
    }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "singlestat",
   "description": "所有组件的内存Request总和",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 21 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests_memory_bytes{node!=\"\"} * on(pod, namespace) group_left(phase) (kube_pod_status_phase{phase!=\"Failed\",phase!=\"Succeeded\"} == 1) * on(namespace, pod) group_left(label_service_name) (kube_pod_info_with_label{namespace=~\".*\",pod=~\".*\",label_service_name!=\"\"}))"
    }
   ]
  },
  {
   "title": "Network Transmit Rate of components",
   "type": "graph",
   "description": "各个组件的网络发送速率",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by(label_service_name) (container_network_transmit_bytes_total_irate5m_with_label{label_service_name!=\"\", pod_name=~\".*\"})",
     "legendFormat": "{{label_service_name}}"
    }
   ]
  },
  {
   "title": "Network Receive Rate of components",
   "type": "graph",
   "description": "各个组件的网络接收速率",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by(label_service_name) (container_network_receive_bytes_total_irate5m_with_label{label_service_name!=\"\", pod_name=~\".*\"})",
     "legendFormat": "{{label_service_name}}"
    }
   ]
  },
  {
   "title": "Client Error Code",
   "type": "graph",
   "description": "各个组件15分钟内各API 4xx状态码统计的总和",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(code,service) (delta({code=~\"4.*\",__name__=~\".*requests_total\",endpoint!~\".*[pP]ing.*\",handler!~\".*[pP]ing.*\"}[15m]) * on(pod) group_left(label_service_name) (kube_pod_labels{label_service_name!=\"\"}))",
     "legendFormat": "{{service}}  {{code}}"
    }
   ]
  },
  {
   "title": "Server Error Code",
   "type": "graph",
   "description": "各个组件15分钟内API 5xx状态码统计的总和",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(code,service) (delta({code=~\"5..\",__name__=~\".*requests_total\",endpoint!~\".*[pP]ing.*\",handler!~\".*[pP]ing.*\",}[15m]) * on(pod) group_left(label_service_name) (kube_pod_labels{label_service_name!=\"\"}))",
     "legendFormat": "{{service}} {{code}}"
    }
   ]
  }
 ]
}