{
 "title": "CoreDNS",
 "description": "A dashboard for the CoreDNS DNS server.",
 "tags": [
  "dns",
  "coredns"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(up{job=\"$job\"},namespace)"
   },
   {
    "name": "pod",
    "label": "Instance",
    "query": "label_values(up{job=\"$job\"},pod)"
   },
   { "name": "job", "query": "kube-dns" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total",
   "type": "singlestat",
   "description": "组件实例总数",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "UP",
   "type": "singlestat",
   "description": "组件在线实例数量",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Down",
   "type": "singlestat",
   "description": "组件离线实例数量",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}) - sum(up{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Pod Info",
   "type": "table",
   "description": "组件中所有Pod的详细信息及状态",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Panic Rate",
   "type": "graph",
   "description": "过去5分钟内，CoreDNS异常发生频率（次/s）",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(coredns_panic_count_total{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Duration of Health Query Group  By Quantile",
   "type": "graph",
   "description": "过去5分钟内，CoreDNS健康查询的延迟时间，按分位数分组",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, avg by (pod,le)(rate(coredns_health_request_duration_seconds_bucket{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m])))",
     "legendFormat": "{{pod}}/0.50"
    },
    {
     "expr": "histogram_quantile(0.9, avg by (pod,le)(rate(coredns_health_request_duration_seconds_bucket{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m])))",
     "legendFormat": "{{pod}}/0.90"
    },
    {
     "expr": "histogram_quantile(0.99, avg by (pod,le)(rate(coredns_health_request_duration_seconds_bucket{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m])))",
     "legendFormat": "{{pod}}/0.99"
    }
   ]
  },
  {
   "title": "Average Duration of Health Query",
   "type": "graph",
   "description": "过去5分钟内，CoreDNS健康查询的平均延迟时间",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(coredns_health_request_duration_seconds_sum{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m]) / delta(coredns_health_request_duration_seconds_count{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "graph",
   "description": "Coredns实例的CPU使用情况，每一个点都是以过去5分钟为时间片来统计的，单位是Core",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (pod_name) (container_cpu_usage_seconds_total_irate5m_with_label{namespace=\"$namespace\",pod_name=~\"$pod\"})",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "avg by (pod_name) (kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "request"
    },
    {
     "expr": "avg by (pod_name) (kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "description": "Coredns的网络流量情况",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod_name=~\"$pod\"}[5m]))",
     "legendFormat": "{{pod_name}}.network_received"
    },
    {
     "expr": "sum by (pod_name) (rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod_name=~\"$pod\"}[5m]))",
     "legendFormat": "{{pod_name}}.network_transmitted"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Cache Size Group By Type",
   "type": "graph",
   "description": "CoreDNS缓存的元素总数，按缓存类型分组",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(type) (coredns_cache_size{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"})",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(coredns_cache_size{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Cache Hit Rate Group By Type",
   "type": "graph",
   "description": "过去5分钟内，CoreDNS缓存命中频率(次/s)，按 缓存类型分组",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(type) (rate(coredns_cache_hits_total{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cache Miss Rate",
   "type": "graph",
   "description": "过去5分钟内，CoreDNS缓存未命中频率（次/s）",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(coredns_cache_misses_total{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m]))",
     "legendFormat": "$pod"
    }
   ]
  },
  { "title": "Request and Response", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Average Rate of DNS Requests",
   "type": "graph",
   "description": "过去5分钟内，CoreDNS DNS请求的平均增长速率",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(coredns_dns_request_count_total{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m]))",
     "legendFormat": "$pod"
    }
   ]
  },
  {
   "title": "Duration of DNS Requests Group By Quantile",
   "type": "graph",
   "description": "过去5分钟内，CoreDNS DNS请求的延迟时间，按分位数分组",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, avg by (pod,le)(rate(coredns_dns_request_duration_seconds_bucket{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m])))",
     "legendFormat": "{{pod}}/0.50"
    },
    {
     "expr": "histogram_quantile(0.9, avg by (pod,le)(rate(coredns_dns_request_duration_seconds_bucket{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m])))",
     "legendFormat": "{{pod}}/0.90"
    },
    {
     "expr": "histogram_quantile(0.99, avg by (pod,le)(rate(coredns_dns_request_duration_seconds_bucket{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m])))",
     "legendFormat": "{{pod}}/0.99"
    }
   ]
  },
  {
   "title": "Average Duration of DNS Requests",
   "type": "graph",
   "description": "过去5分钟内，CoreDNS DNS请求的平均延迟时间",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(coredns_dns_request_duration_seconds_sum{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m]) / delta(coredns_dns_request_duration_seconds_count{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m])",
     "legendFormat": "{{pod}} "
    }
   ]
  },
  {
   "title": "Average Rate of DNS Requests Group By Protocol",
   "type": "graph",
   "description": "过去5分钟内，DNS请求的平均增长速率，按请求协议类型分组",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_count_total{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m])) by (proto)",
     "legendFormat": "{{proto}}"
    },
    {
     "expr": "sum(rate(coredns_dns_request_count_total{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Average Rate of DNS Requests Group By Zone and Type",
   "type": "graph",
   "description": "过去5分钟内，DNS请求的平均增长速率，按DNS区域和类型分组",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(zone,type) (rate(coredns_dns_request_type_count_total{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m]))",
     "legendFormat": "{{zone}}/{{type}}"
    },
    {
     "expr": "sum by(zone) (rate(coredns_dns_request_type_count_total{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m]))",
     "legendFormat": "{{zone}}/total"
    }
   ]
  },
  {
   "title": "Requests Size Group By Protocol and Quantile",
   "type": "graph",
   "description": "过去5分钟内，DNS请求的大小，按请求协议和分位数分组",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_size_bytes_bucket{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m])) by (le,proto))",
     "legendFormat": "{{proto}}/0.99 "
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_request_size_bytes_bucket{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m])) by (le,proto))",
     "legendFormat": "{{proto}}/0.90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_size_bytes_bucket{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m])) by (le,proto))",
     "legendFormat": "{{proto}}/0.50"
    }
   ]
  },
  {
   "title": "Average Rate of DNS Response  Group By Status Codes",
   "type": "graph",
   "description": "过去5分钟内，DNS响应的返回速率，按返回码分组",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_response_rcode_count_total{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m])) by (rcode)",
     "legendFormat": "{{rcode}}"
    }
   ]
  },
  {
   "title": "Average Size of DNS Response Group By Protocol and Quantile",
   "type": "graph",
   "description": "过去5分钟内，DNS响应的平均大小，按请求协议类型和分位数分组",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_response_size_bytes_bucket{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m])) by (le,proto)) ",
     "legendFormat": "{{proto}}/0.99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_response_size_bytes_bucket{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m])) by (le,proto)) ",
     "legendFormat": "{{proto}}/0.90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_response_size_bytes_bucket{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m])) by (le,proto)) ",
     "legendFormat": "{{proto}}/0.50"
    }
   ]
  },
  { "title": "Forward", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Average Rate of Forward Requests",
   "type": "graph",
   "description": "过去5分钟内，CoreDNS Forward请求的平均增长速率（次/s）[mod]：Forward替換了Proxy",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(coredns_forward_request_count_total{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m]))",
     "legendFormat": "$pod"
    }
   ]
  },
  {
   "title": "Duration of Forward Requests Group By Quantile",
   "type": "graph",
   "description": "过去5分钟内，CoreDNS Forward请求的延迟时间，按分位数分组[mod]：Forward替換了Proxy",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 61 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, avg by (pod,le)(rate(coredns_forward_request_duration_seconds_bucket{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m])))",
     "legendFormat": "{{pod}}/0.50"
    },
    {
     "expr": "histogram_quantile(0.9, avg by (pod,le)(rate(coredns_forward_request_duration_seconds_bucket{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m])))",
     "legendFormat": "{{pod}}/0.90"
    },
    {
     "expr": "histogram_quantile(0.99, avg by (pod,le)(rate(coredns_forward_request_duration_seconds_bucket{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m])))",
     "legendFormat": "{{pod}}/0.99"
    }
   ]
  },
  {
   "title": "Average Duration of Forward Requests Group By Protocol",
   "type": "graph",
   "description": "过去5分钟内，CoreDNS Forward请求的平均延迟时间，按协议类型分钟[mod]：Forward替換了Proxy",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 61 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(coredns_forward_request_duration_seconds_sum{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m]) / delta(coredns_forward_request_duration_seconds_count{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m])",
     "legendFormat": "{{pod}} {{proto}} "
    }
   ]
  }
 ]
}