{
 "title": "Kube-Proxy",
 "description": "A dashboard for the kube-proxy.",
 "tags": [ "kube-proxy" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(up{job=\"$job\"},namespace)"
   },
   {
    "name": "pod",
    "label": "Instance",
    "query": "label_values(up{job=\"$job\"},pod)"
   },
   { "name": "job", "query": "kube-proxy" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total",
   "type": "singlestat",
   "description": "组件实例总数",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "UP",
   "type": "singlestat",
   "description": "组件在线实例数量",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Down",
   "type": "singlestat",
   "description": "组件离线实例数量",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}) - sum(up{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Pod Info",
   "type": "table",
   "description": "组件中所有Pod的详细信息及状态",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  { "title": "API Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "API Requests Average Latency Group by Handler",
   "type": "graph",
   "description": "过去5分钟内，组件中每个Pod的平均延迟，按handler分组[invalid]：未筛选出数据",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum by(handler)(delta(http_request_duration_microseconds_sum{job=\"$job\",namespace=\"$namespace\",pod=~\"$pod\"}[5m])) / sum by(handler) (delta(http_request_duration_microseconds_count{job=\"$job\",namespace=\"$namespace\",pod=~\"$pod\"}[5m]))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "API Requests Average Latency Group by Quantile",
   "type": "graph",
   "description": "组件中请求延迟统计，分别展示分位数0.5、0.9、0.99的数据[invalid]：未筛选出数据",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum by(handler,quantile) (http_request_duration_microseconds{job=\"$job\",namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "{{handler}}/{{quantile}}"
    }
   ]
  },
  {
   "title": "API Requests Size Group by Handler and Quantile",
   "type": "graph",
   "description": "组件API请求的大小，按Handler和分位数分组[invalid]：未筛选出数据",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(http_request_size_bytes{job=\"$job\",namespace=\"$namespace\",pod=~\"$pod\"}) by(handler,quantile)",
     "legendFormat": "{{handler}}/{{quantile}}"
    }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "graph",
   "description": "Coredns实例的CPU使用情况，每一个点都是以过去5分钟为时间片来统计的，单位是Core",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (pod_name) (container_cpu_usage_seconds_total_irate5m_with_label{namespace=\"$namespace\",pod_name=~\"$pod\"})",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "avg by (pod_name) (kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "request"
    },
    {
     "expr": "avg by (pod_name) (kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "description": "Coredns的网络流量情况",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod_name=~\"$pod\"}[5m]))",
     "legendFormat": "{{pod_name}}.network_received"
    },
    {
     "expr": "sum by (pod_name) (rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod_name=~\"$pod\"}[5m]))",
     "legendFormat": "{{pod_name}}.network_transmitted"
    }
   ]
  },
  { "title": "Rest Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Rest Client Average Rate  Group By Status Code",
   "type": "graph",
   "description": "过去5分钟内，组件内Rest Client的请求速率，按返回码分组",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"$job\",namespace=\"$namespace\",pod=~\"$pod\"}[5m])) by(code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Rest Client Requests Latency Group by Verb and URL",
   "type": "graph",
   "description": "过去5分钟内，组件发出的Rest API请求的平均延迟，按Verb和URL进行分组",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, avg(rate(rest_client_request_latency_seconds_bucket{job=\"$job\",namespace=\"$namespace\",pod=~\"$pod\"}[5m])) by (url,verb,le))",
     "legendFormat": "{{verb}} {{url}} 0.99"
    },
    {
     "expr": "histogram_quantile(0.9, avg(rate(rest_client_request_latency_seconds_bucket{job=\"$job\",namespace=\"$namespace\",pod=~\"$pod\"}[5m])) by (url,verb,le))",
     "legendFormat": "{{verb}} {{url}} 0.9"
    },
    {
     "expr": "histogram_quantile(0.5, avg(rate(rest_client_request_latency_seconds_bucket{job=\"$job\",namespace=\"$namespace\",pod=~\"$pod\"}[5m])) by (url,verb,le))",
     "legendFormat": "{{verb}} {{url}} 0.5"
    }
   ]
  },
  {
   "title": "Client Requests Average Latency",
   "type": "graph",
   "description": "过去5分钟内，组件Rest Client请求的平均延迟时间",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by(url, verb) (delta  (rest_client_request_latency_seconds_sum{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m])) / sum by(url,verb) (delta (rest_client_request_latency_seconds_count{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m]))",
     "legendFormat": "{{verb}} {{url}}"
    }
   ]
  },
  { "title": "Sync Proxy Rules", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Average Rate of Sync Proxy Rules",
   "type": "graph",
   "description": "过去5分钟内，Kube-proxy同步代理规则请求的平均增长速率（次/s）",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(coredns_proxy_request_count_total{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m])) or on() vector(0)",
     "legendFormat": "$pod"
    }
   ]
  },
  {
   "title": "Latency of Sync Proxy Rules Group By Quantile",
   "type": "graph",
   "description": "过去5分钟内，Kube-proxy同步代理规则请求的延迟时间，按分位数分组",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, avg by (pod,le)(rate(kubeproxy_sync_proxy_rules_latency_microseconds_bucket{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m])))",
     "legendFormat": "{{pod}}/0.50"
    },
    {
     "expr": "histogram_quantile(0.9, avg by (pod,le)(rate(kubeproxy_sync_proxy_rules_latency_microseconds_bucket{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m])))",
     "legendFormat": "{{pod}}/0.90"
    },
    {
     "expr": "histogram_quantile(0.99, avg by (pod,le)(rate(kubeproxy_sync_proxy_rules_latency_microseconds_bucket{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m])))",
     "legendFormat": "{{pod}}/0.99"
    }
   ]
  },
  {
   "title": "Average Latency of Sync Proxy Rules",
   "type": "graph",
   "description": "过去5分钟内，Kube-proxy同步代理规则请求的平均延迟时间",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "delta(kubeproxy_sync_proxy_rules_latency_microseconds_sum{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m]) / delta(kubeproxy_sync_proxy_rules_latency_microseconds_count{namespace=\"$namespace\",pod=~\"$pod\",job=\"$job\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}