{
 "title": "Kube-Controller-Manager",
 "tags": [ "controller-manager" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": "query_result(process_cpu_seconds_total{job=\"kube-controller-manager\"})"
   },
   { "name": "namespace", "query": "kube-system" },
   { "name": "pod", "query": "kube-controller-manager.*" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UP",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{job=\"kube-controller-manager\"})"
    }
   ]
  },
  {
   "title": "Restarted",
   "type": "singlestat",
   "description": "过去5分钟Apiserver实例重启的次数",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (delta(kube_pod_container_status_restarts_total{namespace=\"$namespace\",pod=~\"$pod\"}[5m]))"
    }
   ]
  },
  {
   "title": "Pod Info",
   "type": "table",
   "description": "组件中所有Pod的详细信息及状态",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "graph",
   "description": "Apiserver实例的CPU使用情况，每一个点都是以过去5分钟为时间片来统计的，单位是Core",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (pod_name) (container_cpu_usage_seconds_total_irate5m_with_label{namespace=\"$namespace\",pod_name=~\"$pod\"})",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "avg by (pod_name) (kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "request"
    },
    {
     "expr": "avg by (pod_name) (kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "graph",
   "description": "Apiserver实例的内存使用情况",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (pod_name) (container_memory_usage_bytes_without_cache_with_label{namespace=\"$namespace\",pod_name=~\"$pod\"})",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "avg by (pod_name) (kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "request"
    },
    {
     "expr": "avg by (pod_name) (kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Controller Manager Request Latency Group by Quantile",
   "type": "graph",
   "description": "过去5分钟内Controller Manager处理请求的平均延迟，按照请求延时的分布进行分组[invalid]：未筛选出数据",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(http_request_duration_microseconds{job=\"kube-controller-manager\", quantile=\"0.99\"})",
     "legendFormat": "99th latency"
    },
    {
     "expr": "avg(http_request_duration_microseconds{job=\"kube-controller-manager\", quantile=\"0.9\"})",
     "legendFormat": "90th latency"
    },
    {
     "expr": "avg(http_request_duration_microseconds{job=\"kube-controller-manager\", quantile=\"0.5\"})",
     "legendFormat": "50th latency"
    }
   ]
  },
  {
   "title": "Rest Client Request Latency Group by URL",
   "type": "graph",
   "description": "过去5分钟内Controller Manager发出的请求的平均延迟，按照请求的URL进行分组",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, avg(rate(rest_client_request_latency_seconds_bucket{job=\"kube-controller-manager\", instance=~\"$Instance.*\"}[5m])) by (url, le)) ",
     "legendFormat": " {{url}}"
    }
   ]
  },
  {
   "title": "Controller Manager Queue Latency Group by Resource",
   "type": "graph",
   "description": "过去5分钟内Controller Manager资源排队延时的0.99分位，按照资源进行分组[invalid]：指标项不存在",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(replicaset_queue_latency{quantile=\"0.99\", job=\"kube-controller-manager\", instance=~\"$Instance.*\"})",
     "legendFormat": "replicaset 99th"
    },
    {
     "expr": "avg(deployment_queue_latency{quantile=\"0.99\", job=\"kube-controller-manager\", instance=~\"$Instance.*\"})",
     "legendFormat": "deployment 99th"
    },
    {
     "expr": "avg(daemonset_queue_latency{quantile=\"0.99\", job=\"kube-controller-manager\", instance=~\"$Instance.*\"})",
     "legendFormat": "daemonset 99th"
    },
    {
     "expr": "avg(statefulset_queue_latency{quantile=\"0.99\", job=\"kube-controller-manager\", instance=~\"$Instance.*\"})",
     "legendFormat": "statefulset 99th"
    },
    {
     "expr": "avg(volumes_queue_latency{quantile=\"0.99\", job=\"kube-controller-manager\", instance=~\"$Instance.*\"})",
     "legendFormat": "volumes 99th"
    },
    {
     "expr": "avg(pvcs_queue_latency{quantile=\"0.99\", job=\"kube-controller-manager\", instance=~\"$Instance.*\"})",
     "legendFormat": "pvcs 99th"
    },
    {
     "expr": "avg(job_queue_latency{quantile=\"0.99\", job=\"kube-controller-manager\", instance=~\"$Instance.*\"})",
     "legendFormat": "job 99th"
    }
   ]
  },
  {
   "title": "Controller Manager Work Latency Group by Resource",
   "type": "graph",
   "description": "过去5分钟内Controller Manager资源处理延时的0.99分位，按照资源进行分组[invalid]：指标项不存在",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(replicaset_work_duration{quantile=\"0.99\", job=\"kube-controller-manager\", instance=~\"$Instance.*\"})",
     "legendFormat": "replicaset 99th"
    },
    {
     "expr": "avg(deployment_work_duration{quantile=\"0.99\", job=\"kube-controller-manager\", instance=~\"$Instance.*\"})",
     "legendFormat": "deployment 99th"
    },
    {
     "expr": "avg(daemonset_work_duration{quantile=\"0.99\", job=\"kube-controller-manager\", instance=~\"$Instance.*\"})",
     "legendFormat": "daemonset 99th"
    },
    {
     "expr": "avg(statefulset_work_duration{quantile=\"0.99\", job=\"kube-controller-manager\", instance=~\"$Instance.*\"})",
     "legendFormat": "statefulset 99th"
    },
    {
     "expr": "avg(volumes_work_duration{quantile=\"0.99\", job=\"kube-controller-manager\", instance=~\"$Instance.*\"})",
     "legendFormat": "volumes 99th"
    },
    {
     "expr": "avg(pvcs_work_duration{quantile=\"0.99\", job=\"kube-controller-manager\", instance=~\"$Instance.*\"})",
     "legendFormat": "pvcs 99th"
    },
    {
     "expr": "avg(job_work_duration{quantile=\"0.99\", job=\"kube-controller-manager\", instance=~\"$Instance.*\"})",
     "legendFormat": "job 99th"
    }
   ]
  },
  {
   "title": "Controller Manager Adds Group by Resource",
   "type": "graph",
   "description": "过去5分钟内Controller Manager新增的资源数量，按照资源类型进行分组[invalid]：指标项不存在",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(increase(replicaset_adds{job=\"kube-controller-manager\", instance=~\"$Instance.*\"}[5m]))",
     "legendFormat": "replicaset"
    },
    {
     "expr": "avg(increase(deployment_adds{job=\"kube-controller-manager\", instance=~\"$Instance.*\"}[5m]))",
     "legendFormat": "deployment"
    },
    {
     "expr": "avg(increase(daemonset_adds{job=\"kube-controller-manager\", instance=~\"$Instance.*\"}[5m]))",
     "legendFormat": "daemonset"
    },
    {
     "expr": "avg(increase(statefulset_adds{job=\"kube-controller-manager\", instance=~\"$Instance.*\"}[5m]))",
     "legendFormat": "statefulset"
    },
    {
     "expr": "avg(increase(volumes_adds{job=\"kube-controller-manager\", instance=~\"$Instance.*\"}[5m]))",
     "legendFormat": "volumes"
    },
    {
     "expr": "avg(increase(pvcs_adds{job=\"kube-controller-manager\", instance=~\"$Instance.*\"}[5m]))",
     "legendFormat": "pvcs"
    },
    {
     "expr": "avg(increase(job_adds{job=\"kube-controller-manager\", instance=~\"$Instance.*\"}[5m]))",
     "legendFormat": "job"
    }
   ]
  },
  {
   "title": "Controller Manager Depth Group by Resource",
   "type": "graph",
   "description": "当前Controller Manager资源排队深度[invalid]：指标项不存在",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(replicaset_depth{job=\"kube-controller-manager\", instance=~\"$Instance.*\"})",
     "legendFormat": "replicaset"
    },
    {
     "expr": "avg(deployment_depth{job=\"kube-controller-manager\", instance=~\"$Instance.*\"})",
     "legendFormat": "deployment"
    },
    {
     "expr": "avg(daemonset_depth{job=\"kube-controller-manager\", instance=~\"$Instance.*\"})",
     "legendFormat": "daemonset"
    },
    {
     "expr": "avg(statefulset_depth{job=\"kube-controller-manager\", instance=~\"$Instance.*\"})",
     "legendFormat": "statefulset"
    },
    {
     "expr": "avg(volumes_depth{job=\"kube-controller-manager\", instance=~\"$Instance.*\"})",
     "legendFormat": "volumes"
    },
    {
     "expr": "avg(pvcs_depth{job=\"kube-controller-manager\", instance=~\"$Instance.*\"})",
     "legendFormat": "pvcs"
    },
    {
     "expr": "avg(job_depth{job=\"kube-controller-manager\", instance=~\"$Instance.*\"})",
     "legendFormat": "job"
    }
   ]
  },
  {
   "title": "Controller Manager Rest Client Request Count Group by Response Code",
   "type": "graph",
   "description": "过去5分钟Controller Manager发出的请求数，按照返回码进行分组",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (increase(rest_client_requests_total{job=\"kube-controller-manager\", instance=~\"$Instance.*\"}[5m]))",
     "legendFormat": "{{code}} requests"
    }
   ]
  },
  {
   "title": "Goroutines Group by Instance",
   "type": "graph",
   "description": "Scheduler实例的goroutines数量",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (pod) (go_goroutines{namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$Instance.*\"})",
     "legendFormat": "{{pod}}/goroutines"
    }
   ]
  }
 ]
}