{
 "title": "Kube-Apiserver",
 "tags": [ "apiserver" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": "query_result(apiserver_request_count{job=\"apiserver\"})"
   },
   { "name": "namespace", "query": "kube-system" },
   { "name": "pod", "query": "kube-apiserver.*" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UP",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{job=\"apiserver\"})"
    }
   ]
  },
  {
   "title": "Restarted",
   "type": "singlestat",
   "description": "过去5分钟Apiserver实例重启的次数",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (delta(kube_pod_container_status_restarts_total{namespace=\"$namespace\",pod=~\"$pod\"}[5m]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "singlestat",
   "description": "过去5分钟接收到的api请求数",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (increase(apiserver_request_count{job=\"apiserver\",instance=~\"$Instance.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Pod Info",
   "type": "table",
   "description": "组件中所有Pod的详细信息及状态",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "graph",
   "description": "Apiserver实例的CPU使用情况，每一个点都是以过去5分钟为时间片来统计的，单位是Core",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (pod_name) (container_cpu_usage_seconds_total_irate5m_with_label{namespace=\"$namespace\",pod_name=~\"$pod\"})",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "avg by (pod_name) (kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "request"
    },
    {
     "expr": "avg by (pod_name) (kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "graph",
   "description": "Apiserver实例的内存使用情况",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (pod_name) (container_memory_usage_bytes_without_cache_with_label{namespace=\"$namespace\",pod_name=~\"$pod\"})",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "avg by (pod_name) (kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "request"
    },
    {
     "expr": "avg by (pod_name) (kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Apiserver Request Latency Group by Quantile",
   "type": "graph",
   "description": "过去5分钟内Apiserver处理请求的平均延迟，按照请求延时的分布进行分组",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, avg(rate(apiserver_request_latencies_bucket{job=\"apiserver\", instance=~\"$Instance.*\"}[5m])) by (le))",
     "legendFormat": "99th latency"
    },
    {
     "expr": "histogram_quantile(0.9, avg(rate(apiserver_request_latencies_bucket{job=\"apiserver\", instance=~\"$Instance.*\"}[5m])) by (le))",
     "legendFormat": "90th latency"
    },
    {
     "expr": "histogram_quantile(0.5, avg(rate(apiserver_request_latencies_bucket{job=\"apiserver\", instance=~\"$Instance.*\"}[5m])) by (le))",
     "legendFormat": "50th latency"
    }
   ]
  },
  {
   "title": "Apiserver Request Latency Group by Verb",
   "type": "graph",
   "description": "过去5分钟内Apiserver处理请求的平均延迟，按照请求的方法进行分组",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, avg(rate(apiserver_request_latencies_bucket{job=\"apiserver\", instance=~\"$Instance.*\"}[5m])) by (verb, le))",
     "legendFormat": " {{verb}} latency"
    }
   ]
  },
  {
   "title": "Apiserver Request Latency Group by Resource",
   "type": "graph",
   "description": "过去5分钟内Apiserver处理请求的平均延迟(Watch请求不计算在内)，按照请求的资源进行分组",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, avg(rate(apiserver_request_latencies_bucket{job=\"apiserver\", instance=~\"$Instance.*\",verb!=\"WATCH\"}[5m])) by (resource, le)) > 0",
     "legendFormat": " {{resource}}"
    }
   ]
  },
  {
   "title": "Apiserver Request Count Group by Response Code",
   "type": "graph",
   "description": "过去5分钟apiserver请求数，按照返回码进行分组",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (increase(rest_client_requests_total{job=\"apiserver\", instance=~\"$Instance.*\"}[5m])) > 0",
     "legendFormat": "{{code}} requests"
    }
   ]
  },
  {
   "title": "Apiserver Admission Webhook Latency",
   "type": "graph",
   "description": "过去5分钟内Apiserver的授权Webhook的平均延迟的0.99分位[invalid]：指标项不存在",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, avg(rate(apiserver_admission_webhook_admission_latencies_seconds_bucket{job=\"apiserver\", instance=~\"$Instance.*\"}[5m])) by (name, le)) ",
     "legendFormat": " {{name}}"
    }
   ]
  },
  {
   "title": "Rest Client Request Latency Group by URL",
   "type": "graph",
   "description": "过去5分钟内Apiserver发出的请求的平均延迟，按照请求的URL进行分组",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, avg(rate(rest_client_request_latency_seconds_bucket{job=\"apiserver\", instance=~\"$Instance.*\"}[5m])) by (url, le)) ",
     "legendFormat": " {{url}}"
    }
   ]
  },
  { "title": "Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Apiserver Request Count",
   "type": "graph",
   "description": "过去5分钟内apiserver处理的总的请求数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (increase(apiserver_request_count{job=\"apiserver\", instance=~\"$Instance.*\"}[5m]))",
     "legendFormat": "requests total"
    }
   ]
  },
  {
   "title": "Apiserver Request Count Group by Verb",
   "type": "graph",
   "description": "过去5分钟内apiserver处理的请求数，按照请求方法进行分组",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(verb)(increase(apiserver_request_count{job=\"apiserver\", instance=~\"$Instance.*\"}[5m]))",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "Apiserver Request Count Group by Resource",
   "type": "graph",
   "description": "过去5分钟内apiserver处理的请求数，按照请求资源类型进行分组",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(resource)(increase(apiserver_request_count{job=\"apiserver\", instance=~\"$Instance.*\"}[5m]))",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Apiserver Request Count Group by Client",
   "type": "graph",
   "description": "过去5分钟内apiserver处理的请求数，按照请求客户端进行分组",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(client)(increase(apiserver_request_count{job=\"apiserver\", instance=~\"$Instance.*\"}[5m]))",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "Apiserver Registered Watchers Group by Kind",
   "type": "graph",
   "description": "当前apiserver已经注册的Watcher数，按照资源类型进行分组",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kind) (apiserver_registered_watchers{job=\"apiserver\", instance=~\"$Instance.*\"})",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Active Long-Running Apiserver Requests Count Group by  Resource and Verb",
   "type": "graph",
   "description": "当前apiserver长期处于活跃状态的请求数，按照资源和请求类型进行分组",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (resource, verb) (apiserver_longrunning_gauge{job=\"apiserver\", instance=~\"$Instance.*\"})",
     "legendFormat": "{{resource}} {{verb}}"
    }
   ]
  },
  {
   "title": "Apiserver Admission Controller Admission Latency Group by Name",
   "type": "graph",
   "description": "过去5分钟内Apiserver处理请求时，Contorller花在鉴权上的平均延迟的0.99分位[invalid]：指标项不存在",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, avg(rate(apiserver_admission_controller_admission_latencies_seconds_bucket{job=\"apiserver\", instance=~\"$Instance.*\"}[5m])) by (name, le))",
     "legendFormat": "{{name}} 99th latency"
    }
   ]
  },
  {
   "title": "Apiserver Admission Step Admission Latency Group by Name",
   "type": "graph",
   "description": "过去5分钟内Apiserver处理请求时，Contorller花在鉴权上的平均阶段延迟的0.99分位，按照操作和准入类型进行分组[invalid]：未筛选出数据",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, avg(rate(apiserver_admission_step_admission_latencies_seconds_bucket{job=\"apiserver\", instance=~\"$Instance.*\"}[5m])) by (operation, type, le))",
     "legendFormat": "{{operation}} {{type}} 99th latency"
    }
   ]
  }
 ]
}