{
 "title": "Kube-Etcd",
 "description": "etcd sample Grafana dashboard with Prometheus",
 "tags": [ "etcd" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(etcd_server_has_leader, job)"
   },
   { "name": "namespace", "query": "kube-system" },
   { "name": "pod", "query": "etcd-.*" }
  ]
 },
 "panels": [
  {
   "title": "UP",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(etcd_server_has_leader{job=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Restarted",
   "type": "singlestat",
   "description": "过去5分钟Scheduler实例重启的次数",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (delta(kube_pod_container_status_restarts_total{namespace=\"$namespace\",pod=~\"$pod\"}[5m]))"
    }
   ]
  },
  {
   "title": "ETCD Objects Count Group by Resource",
   "type": "graph",
   "description": "etcd资源对象计数，按照请求资源类型进行分组[mod]：原先的注释错误",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (resource) (etcd_object_counts)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "graph",
   "description": "Scheduler实例的CPU使用情况，每一个点都是以过去5分钟为时间片来统计的，单位是Core",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (pod_name) (container_cpu_usage_seconds_total_irate5m_with_label{namespace=\"$namespace\",pod_name=~\"$pod\"})",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "avg by (pod_name) (kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "request"
    },
    {
     "expr": "avg by (pod_name) (kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "graph",
   "description": "Scheduler实例的内存使用情况",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (pod_name) (container_memory_usage_bytes_without_cache_with_label{namespace=\"$namespace\",pod_name=~\"$pod\"})",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "avg by (pod_name) (kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "request"
    },
    {
     "expr": "avg by (pod_name) (kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "RPC Rate in Last 5m",
   "type": "graph",
   "description": "集群中的etcd过去5分钟的RPC的次数，以及RPC失败的次数",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{job=\"$cluster\",grpc_type=\"unary\"}[5m]))",
     "legendFormat": "RPC Rate"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"$cluster\",grpc_type=\"unary\",grpc_code!=\"OK\"}[5m]))",
     "legendFormat": "RPC Failed Rate"
    }
   ]
  },
  {
   "title": "Raft Proposals in Last 5m",
   "type": "graph",
   "description": "集群中的etcd过去5分钟的提议速率，分别对应提议提交、失败、排队、应用",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_server_proposals_failed_total{job=\"$cluster\"}[5m]))",
     "legendFormat": "Proposal Failure Rate"
    },
    {
     "expr": "sum(etcd_server_proposals_pending{job=\"$cluster\"})",
     "legendFormat": "Proposal Pending Total"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_committed_total{job=\"$cluster\"}[5m]))",
     "legendFormat": "Proposal Commit Rate"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_applied_total{job=\"$cluster\"}[5m]))",
     "legendFormat": "Proposal Apply Rate"
    }
   ]
  },
  {
   "title": "Disk Sync Duration Group by Instance",
   "type": "graph",
   "description": "集群中的etcd的实例过去5分钟WAL同步时间和DB同步时间",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{job=\"$cluster\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} WAL fsync"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{job=\"$cluster\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} DB fsync"
    }
   ]
  },
  {
   "title": "ETCD DB Size Group by Instance",
   "type": "graph",
   "description": "ETCD实例的数据库大小",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (etcd_mvcc_db_total_size_in_bytes{job=\"$cluster\"})",
     "legendFormat": "{{instance}} DB Size"
    }
   ]
  },
  {
   "title": "Active Watch and Lease Streams",
   "type": "graph",
   "description": "集群中的etcd的当前还在活跃的watcher数和lease数",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grpc_server_started_total{job=\"$cluster\",grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{job=\"$cluster\",grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"})",
     "legendFormat": "Watch Streams"
    },
    {
     "expr": "sum(grpc_server_started_total{job=\"$cluster\",grpc_service=\"etcdserverpb.Lease\"}) - sum(grpc_server_handled_total{job=\"$cluster\",grpc_service=\"etcdserverpb.Lease\"})",
     "legendFormat": "Lease Streams"
    }
   ]
  },
  {
   "title": "ETCD Leader Elections in Last One Day",
   "type": "graph",
   "description": "过去5分钟内发生ETCD选主的次数",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "changes(etcd_server_leader_changes_seen_total{job=\"$cluster\"}[1d])",
     "legendFormat": "{{instance}} Leader Elections"
    }
   ]
  },
  {
   "title": "Client Traffic In Group by Instance",
   "type": "graph",
   "description": "集群中的etcd的client过去5分钟的网络流量接收速率",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_received_bytes_total{job=\"$cluster\"}[5m])",
     "legendFormat": "{{instance}} Client Traffic In"
    }
   ]
  },
  {
   "title": "Client Traffic Out Group by Instance",
   "type": "graph",
   "description": "集群中的etcd的client过去5分钟的网络流量发送速率",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_sent_bytes_total{job=\"$cluster\"}[5m])",
     "legendFormat": "{{instance}} Client Traffic Out"
    }
   ]
  },
  {
   "title": "Peer Traffic In Group by Instance",
   "type": "graph",
   "description": "集群中的etcd的peer过去5分钟的网络流量接收速率",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_received_bytes_total{job=\"$cluster\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} Peer Traffic In"
    }
   ]
  },
  {
   "title": "Peer Traffic Out Group by Instance",
   "type": "graph",
   "description": "集群中的etcd的peer过去5分钟的网络流量发送速率",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_sent_bytes_total{job=\"$cluster\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} Peer Traffic Out"
    }
   ]
  },
  {
   "title": "Duration of Query  By Quantile",
   "type": "graph",
   "description": "过去5分钟内，etcd响应请求的延迟时间，按分位数分组",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, avg by (pod,le)(rate(etcd_request_duration_seconds_bucket[5m])))",
     "legendFormat": "{{pod}}/0.50"
    },
    {
     "expr": "histogram_quantile(0.9, avg by (pod,le)(rate(etcd_request_duration_seconds_bucket[5m])))",
     "legendFormat": "{{pod}}/0.90"
    },
    {
     "expr": "histogram_quantile(0.99, avg by (pod,le)(rate(etcd_request_duration_seconds_bucket[5m])))",
     "legendFormat": "{{pod}}/0.99"
    }
   ]
  }
 ]
}