{
 "title": "Kubelet",
 "tags": [ "kubelet" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "instance",
    "query": "label_values(kubelet_runtime_operations{cluster=\"$cluster\", job=\"kubelet\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "UP",
   "type": "singlestat",
   "description": "当前正在运行的Kubelet的数量",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{cluster=\"$cluster\", job=\"kubelet\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kubelet_running_pod_count{cluster=\"$cluster\", job=\"kubelet\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Running Container",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kubelet_running_container_count{cluster=\"$cluster\", job=\"kubelet\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Actual Volume Count",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "sum(volume_manager_total_volumes{cluster=\"$cluster\", job=\"kubelet\", instance=~\"$instance\", state=\"actual_state_of_world\"})",
     "legendFormat": "{{`{{instance}}`}}"
    }
   ]
  },
  {
   "title": "Desired Volume Count",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(volume_manager_total_volumes{cluster=\"$cluster\", job=\"kubelet\", instance=~\"$instance\",state=\"desired_state_of_world\"})",
     "legendFormat": "{{`{{instance}}`}}"
    }
   ]
  },
  {
   "title": "Config Error Count",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(kubelet_node_config_error{cluster=\"$cluster\", job=\"kubelet\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{`{{instance}}`}}"
    }
   ]
  },
  {
   "title": "CPU Usage Group by Instance",
   "type": "graph",
   "description": "当前Kubelet消耗的CPU资源，单位是核",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{cluster=\"$cluster\",job=\"kubelet\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage Group by Instance",
   "type": "graph",
   "description": "进程的常驻内存占用量，按照主机实例进行分组",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{cluster=\"$cluster\",job=\"kubelet\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Kubelet Operation Rate Group by Type",
   "type": "graph",
   "description": "过去5分钟内Kubelet执行的操作次数，按照操作类型进行分组",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubelet_runtime_operations{cluster=\"$cluster\",job=\"kubelet\",instance=~\"$instance\"}[5m])) by (operation_type)",
     "legendFormat": "{{operation_type}}"
    }
   ]
  },
  {
   "title": "Kubelet Operation Error Rate Group by Type",
   "type": "graph",
   "description": "过去5分钟内Kubelet执行的操作失败的次数，按照操作类型进行分组",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubelet_runtime_operations_errors{cluster=\"$cluster\",job=\"kubelet\",instance=~\"$instance\"}[5m])) by (operation_type)",
     "legendFormat": "{{operation_type}}"
    }
   ]
  },
  {
   "title": "Kubelet Operation Duration 99th Quantile Group by Type",
   "type": "graph",
   "description": "过去5分钟内Kubelet执行的操作延时的99th分位值",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(kubelet_runtime_operations_latency_microseconds{cluster=\"$cluster\",job=\"kubelet\",instance=~\"$instance\",quantile=\"0.99\"}) by (operation_type)",
     "legendFormat": "{{operation_type}}"
    }
   ]
  },
  {
   "title": "Rest Client Request Duration 99th Quantile",
   "type": "graph",
   "description": "过去5分钟内Kublet发出的Rest请求的平均延迟的99th分位[invalid]：未筛选出数据",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_latency_seconds_bucket{cluster=\"$cluster\",job=\"kubelet\", instance=~\"$instance\"}[5m])) by (verb, url, le))",
     "legendFormat": " {{verb}} {{url}}"
    }
   ]
  },
  {
   "title": "Rest Client Requests Count Group by Response Code",
   "type": "graph",
   "description": "过去5分钟Kubelet发出的Rest请求速率，按照返回码进行分组[invalid]：未筛选出数据",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{cluster=\"$cluster\",job=\"kubelet\", instance=~\"$instance\",code=~\"2..\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{cluster=\"$cluster\",job=\"kubelet\", instance=~\"$instance\",code=~\"3..\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{cluster=\"$cluster\",job=\"kubelet\", instance=~\"$instance\",code=~\"4..\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{cluster=\"$cluster\",job=\"kubelet\", instance=~\"$instance\",code=~\"5..\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Kubelet Pod Start Latency Group by Quantile",
   "type": "graph",
   "description": "Kubelet启动Pod的延迟分布状况",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(kubelet_pod_start_latency_microseconds{cluster=\"$cluster\",job=\"kubelet\",instance=~\"$instance\", quantile=\"0.99\"})",
     "legendFormat": "99th latency"
    },
    {
     "expr": "avg(kubelet_pod_start_latency_microseconds{cluster=\"$cluster\",job=\"kubelet\",instance=~\"$instance\", quantile=\"0.9\"})",
     "legendFormat": "90th latency"
    },
    {
     "expr": "avg(kubelet_pod_start_latency_microseconds{cluster=\"$cluster\",job=\"kubelet\",instance=~\"$instance\", quantile=\"0.5\"})",
     "legendFormat": "50th latency"
    }
   ]
  },
  {
   "title": "Kubelet Pod Worker Start Duration Group by Quantile",
   "type": "graph",
   "description": "Kubelet 的Pod Worker启动的延时分布",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(kubelet_pod_worker_start_latency_microseconds{cluster=\"$cluster\",job=\"kubelet\",instance=~\"$instance\", quantile=\"0.99\"})",
     "legendFormat": "99th latency"
    },
    {
     "expr": "avg(kubelet_pod_worker_start_latency_microseconds{cluster=\"$cluster\",job=\"kubelet\",instance=~\"$instance\", quantile=\"0.9\"})",
     "legendFormat": "90th latency"
    },
    {
     "expr": "avg(kubelet_pod_worker_start_latency_microseconds{cluster=\"$cluster\",job=\"kubelet\",instance=~\"$instance\", quantile=\"0.5\"})",
     "legendFormat": "50th latency"
    }
   ]
  },
  {
   "title": "Kubelet Storage Operation Rate Group by Operation and Volume Plugin",
   "type": "graph",
   "description": "Kubelet过去5分钟内发生的存储操作的次数，按照操作类型和存储类型进行分类",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(storage_operation_duration_seconds_count{cluster=\"$cluster\",job=\"kubelet\",instance=~\"$instance\"}[5m])) by (operation_name, volume_plugin)",
     "legendFormat": "{{volume_plugin}}/{{operation_name}}  "
    }
   ]
  },
  {
   "title": "Kubelet Storage Operation Error Rate Group by Operation and Volume Plugin",
   "type": "graph",
   "description": "Kubelet过去5分钟内发生的存储操作失败的次数，按照操作类型和存储类型进行分类",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(storage_operation_errors_total{cluster=\"$cluster\",job=\"kubelet\",instance=~\"$instance\"}[5m])) by (operation_name, volume_plugin)",
     "legendFormat": "{{volume_plugin}}/{{operation_name}}"
    }
   ]
  },
  {
   "title": "Storage Operation Duration 99th Quantile Group by Operation and Volume Plugin",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(storage_operation_duration_seconds_bucket{cluster=\"$cluster\", job=\"kubelet\", instance=~\"$instance\"}[5m])) by (operation_name, volume_plugin, le))",
     "legendFormat": "{{volume_plugin}}/{{operation_name}}"
    }
   ]
  },
  {
   "title": "Kubelet Cgroup Manager Operation Rate Group by Operation",
   "type": "graph",
   "description": "过去5分钟内Cgroup Manager发生的操作次数，按照操作类型进行分组",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubelet_cgroup_manager_latency_microseconds_count{cluster=\"$cluster\", job=\"kubelet\", instance=~\"$instance\"}[5m])) by (operation_type)",
     "legendFormat": "{{operation_type}}"
    }
   ]
  },
  {
   "title": "Cgroup Manager Operation Latency 99th Quantile",
   "type": "graph",
   "description": "Kubelet的Cgroup Manager操作延迟的99th分位值",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(kubelet_cgroup_manager_latency_microseconds{cluster=\"$cluster\", job=\"kubelet\", instance=~\"$instance\", quantile=\"0.99\"}) by (operation_type)",
     "legendFormat": " {{operation_type}} 99th"
    }
   ]
  },
  {
   "title": "PLEG Relist Rate Group by Instance",
   "type": "graph",
   "description": "Pod Lifecycle Event Generator过去5分钟内重新获取列表的次数",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubelet_pleg_relist_latency_microseconds_count{cluster=\"$cluster\", job=\"kubelet\", instance=~\"$instance\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PLEG Relist Interval Group by Instance and Quantile",
   "type": "graph",
   "description": "Kubelet PLEG重新获取列表间隔的分布状况，按照主机实例进行分组",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(kubelet_pleg_relist_interval_microseconds{cluster=\"$cluster\",job=\"kubelet\",instance=~\"$instance\",quantile=\"0.99\"}) by (instance)",
     "legendFormat": "{{instance}} 99th"
    },
    {
     "expr": "avg(kubelet_pleg_relist_interval_microseconds{cluster=\"$cluster\",job=\"kubelet\",instance=~\"$instance\",quantile=\"0.9\"}) by (instance)",
     "legendFormat": "{{instance}} 90th"
    },
    {
     "expr": "avg(kubelet_pleg_relist_interval_microseconds{cluster=\"$cluster\",job=\"kubelet\",instance=~\"$instance\",quantile=\"0.5\"}) by (instance)",
     "legendFormat": "{{instance}} 50th"
    }
   ]
  },
  {
   "title": "PLEG Relist Duration Group by Instance and Quantile",
   "type": "graph",
   "description": "Kubelet PLEG重新获取列表延时的分布状况，按照主机实例进行分组",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(kubelet_pleg_relist_latency_microseconds{cluster=\"$cluster\",job=\"kubelet\",instance=~\"$instance\",quantile=\"0.99\"}) by (instance)",
     "legendFormat": "{{instance}} 99th"
    },
    {
     "expr": "avg(kubelet_pleg_relist_latency_microseconds{cluster=\"$cluster\",job=\"kubelet\",instance=~\"$instance\",quantile=\"0.9\"}) by (instance)",
     "legendFormat": "{{instance}} 90th"
    },
    {
     "expr": "avg(kubelet_pleg_relist_latency_microseconds{cluster=\"$cluster\",job=\"kubelet\",instance=~\"$instance\",quantile=\"0.5\"}) by (instance)",
     "legendFormat": "{{instance}} 50th"
    }
   ]
  },
  {
   "title": "Goroutines Count Group by Instance",
   "type": "graph",
   "description": "Kubelet的goroutine的数量",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{cluster=\"$cluster\",job=\"kubelet\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}