{
 "title": "Kube-Scheduler",
 "tags": [ "scheduler" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": "query_result(process_cpu_seconds_total{job=\"kube-scheduler\"})"
   },
   { "name": "namespace", "query": "kube-system" },
   { "name": "pod", "query": "kube-scheduler.*" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UP",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{job=\"apiserver\"})"
    }
   ]
  },
  {
   "title": "Restarted",
   "type": "singlestat",
   "description": "过去5分钟Scheduler实例重启的次数",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (delta(kube_pod_container_status_restarts_total{namespace=\"$namespace\",pod=~\"$pod\"}[5m]))"
    }
   ]
  },
  {
   "title": "Pod Info",
   "type": "table",
   "description": "组件中所有Pod的详细信息及状态",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "graph",
   "description": "Scheduler实例的CPU使用情况，每一个点都是以过去5分钟为时间片来统计的，单位是Core",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (pod_name) (container_cpu_usage_seconds_total_irate5m_with_label{namespace=\"$namespace\",pod_name=~\"$pod\"})",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "avg by (pod_name) (kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "request"
    },
    {
     "expr": "avg by (pod_name) (kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "graph",
   "description": "Scheduler实例的内存使用情况",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (pod_name) (container_memory_usage_bytes_without_cache_with_label{namespace=\"$namespace\",pod_name=~\"$pod\"})",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "avg by (pod_name) (kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "request"
    },
    {
     "expr": "avg by (pod_name) (kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Scheduler Request Latency Group by Quantile",
   "type": "graph",
   "description": "过去5分钟内Scheduler处理请求的平均延迟，按照请求延时的分布进行分组[invalid]：未筛选出数据",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(http_request_duration_microseconds{job=\"kube-scheduler\", quantile=\"0.99\"})",
     "legendFormat": "99th latency"
    },
    {
     "expr": "avg(http_request_duration_microseconds{job=\"kube-scheduler\", quantile=\"0.9\"})",
     "legendFormat": "90th latency"
    },
    {
     "expr": "avg(http_request_duration_microseconds{job=\"kube-scheduler\", quantile=\"0.5\"})",
     "legendFormat": "50th latency"
    }
   ]
  },
  {
   "title": "Rest Client Request Latency Group by URL",
   "type": "graph",
   "description": "过去5分钟内Scheduler发出的请求的平均延迟，按照请求的URL进行分组",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, avg(rate(rest_client_request_latency_seconds_bucket{job=\"kube-scheduler\", instance=~\"$Instance.*\"}[5m])) by (url, le)) ",
     "legendFormat": " {{url}}"
    }
   ]
  },
  {
   "title": "Scheduler E2E Scheduling Latency Group by Quantile",
   "type": "graph",
   "description": "过去5分钟内Scheduler调度的平均延时，包括调度算法和绑定时间，按照延时分布分组",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, avg(rate(scheduler_e2e_scheduling_latency_microseconds_bucket{job=\"kube-scheduler\", instance=~\"$Instance.*\"}[5m])) by (le))",
     "legendFormat": "99th latency"
    },
    {
     "expr": "histogram_quantile(0.9, avg(rate(scheduler_e2e_scheduling_latency_microseconds_bucket{job=\"kube-scheduler\", instance=~\"$Instance.*\"}[5m])) by (le))",
     "legendFormat": "90th latency"
    },
    {
     "expr": "histogram_quantile(0.5, avg(rate(scheduler_e2e_scheduling_latency_microseconds_bucket{job=\"kube-scheduler\", instance=~\"$Instance.*\"}[5m])) by (le))",
     "legendFormat": " 50th latency"
    }
   ]
  },
  {
   "title": "Scheduler E2E Binding Latency Group by Quantile",
   "type": "graph",
   "description": "过去5分钟内Scheduler调度的绑定主机的平均延时，按照延时分布分组",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, avg(rate(scheduler_binding_latency_microseconds_bucket{job=\"kube-scheduler\", instance=~\"$Instance.*\"}[5m])) by (le)) > 0",
     "legendFormat": "99th latency"
    },
    {
     "expr": "histogram_quantile(0.9, avg(rate(scheduler_binding_latency_microseconds_bucket{job=\"kube-scheduler\", instance=~\"$Instance.*\"}[5m])) by (le)) > 0",
     "legendFormat": "90th latency"
    },
    {
     "expr": "histogram_quantile(0.5, avg(rate(scheduler_binding_latency_microseconds_bucket{job=\"kube-scheduler\", instance=~\"$Instance.*\"}[5m])) by (le)) > 0",
     "legendFormat": " 50th latency"
    }
   ]
  },
  {
   "title": "Scheduler Scheduling Algorithm Latency Group by Quantile",
   "type": "graph",
   "description": "过去5分钟内Scheduler调度算法的平均延时，按照延时分布分组",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, avg(rate(scheduler_scheduling_algorithm_latency_microseconds_bucket{job=\"kube-scheduler\", instance=~\"$Instance.*\"}[5m])) by (le)) > 0",
     "legendFormat": "99th latency"
    },
    {
     "expr": "histogram_quantile(0.9, avg(rate(scheduler_scheduling_algorithm_latency_microseconds_bucket{job=\"kube-scheduler\", instance=~\"$Instance.*\"}[5m])) by (le)) > 0",
     "legendFormat": "90th latency"
    },
    {
     "expr": "histogram_quantile(0.5, avg(rate(scheduler_scheduling_algorithm_latency_microseconds_bucket{job=\"kube-scheduler\", instance=~\"$Instance.*\"}[5m])) by (le)) > 0",
     "legendFormat": " 50th latency"
    }
   ]
  },
  {
   "title": "Goroutines Group by Instance",
   "type": "graph",
   "description": "Scheduler实例的goroutines数量",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (pod) (go_goroutines{namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$Instance.*\"})",
     "legendFormat": "{{pod}}/goroutines"
    }
   ]
  }
 ]
}