{
 "title": "Kubernetes Components",
 "description": "-",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "API Server Request Rates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (rate(apiserver_request_count{code!~\"2..\"}[5m]))",
     "legendFormat": "Error -{{instance}} "
    },
    {
     "expr": "sum by(instance) (rate(apiserver_request_count[5m]))",
     "legendFormat": "Request - {{instance}}"
    }
   ]
  },
  {
   "title": "API Server Request Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "avg(apiserver_request_latencies_sum / apiserver_request_latencies_count) by (instance)"
    }
   ]
  },
  {
   "title": "Nginx Ingress Request Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(nginx_ingress_controller_nginx_process_requests_total[2m])",
     "legendFormat": "Request Rate"
    }
   ]
  },
  {
   "title": "Controller Manager Queue Depth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(service_depth)", "legendFormat": "Service Depth" },
    { "expr": "sum(volumes_depth)", "legendFormat": "Volumes Depth" },
    { "expr": "sum(replicationmanager_depth)", "legendFormat": "Replication Manager Depth" },
    { "expr": "sum(statefulset_depth)", "legendFormat": "StatefulSet Depth" },
    { "expr": "sum(serviceaccount_depth)", "legendFormat": "Service Account Depth" },
    { "expr": "sum(endpoint_depth)", "legendFormat": "Endpoint Depth" },
    { "expr": "sum(deployment_depth)", "legendFormat": "Deployment Depth" },
    { "expr": "sum(daemonset_depth)", "legendFormat": "DaemonSet Depth" },
    { "expr": "sum(replicaset_depth)" }
   ]
  }
 ]
}