{
 "title": "Node Status",
 "description": "Dashboard to get an overview of one server",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(node_load1, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Node CPU Utilization",
   "type": "graph",
   "description": "当前主机的CPU使用率",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - avg by (cpu) (irate(node_cpu{mode=\"idle\", instance=\"$Node\"}[5m])) * 100",
     "legendFormat": "CPU{{cpu}}"
    }
   ]
  },
  {
   "title": "Node System Load Per Core",
   "type": "graph",
   "description": "当前主机的负载，计算方法是用主机的负载除以CPU核心数",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (host) (label_replace(node_load1{instance=\"$Node\"}, \"host\", \"$1\", \"instance\", \"(.*):.*\")) / avg by (host) (label_replace(machine_cpu_cores, \"host\", \"$1\", \"instance\", \"(.*):.*\")) ",
     "legendFormat": "load.1m"
    },
    {
     "expr": "avg by (host) (label_replace(node_load5{instance=\"$Node\"}, \"host\", \"$1\", \"instance\", \"(.*):.*\")) / avg by (host) (label_replace(machine_cpu_cores, \"host\", \"$1\", \"instance\", \"(.*):.*\")) ",
     "legendFormat": "load.5m"
    },
    {
     "expr": "avg by (host) (label_replace(node_load15{instance=\"$Node\"}, \"host\", \"$1\", \"instance\", \"(.*):.*\")) / avg by (host) (label_replace(machine_cpu_cores, \"host\", \"$1\", \"instance\", \"(.*):.*\")) ",
     "legendFormat": "load.15m"
    }
   ]
  },
  {
   "title": "Node Memory Utilization",
   "type": "graph",
   "description": "当前主机的内存使用状况",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg((node_memory_MemTotal{instance=\"$Node\"} - node_memory_MemFree{instance=\"$Node\"} - node_memory_Buffers{instance=\"$Node\"} - node_memory_Cached{instance=\"$Node\"})/ node_memory_MemTotal{instance=\"$Node\"}) * 100",
     "legendFormat": "used"
    },
    {
     "expr": "avg(node_memory_Buffers{instance=\"$Node\"}/ node_memory_MemTotal{instance=\"$Node\"}) * 100",
     "legendFormat": "buffers"
    },
    {
     "expr": "avg(node_memory_Cached{instance=\"$Node\"}/node_memory_MemTotal{instance=\"$Node\"}) * 100",
     "legendFormat": "cached"
    },
    {
     "expr": "avg(node_memory_MemFree{instance=\"$Node\"}/node_memory_MemTotal{instance=\"$Node\"}) * 100",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "graph",
   "description": "当前主机的磁盘空间利用率和磁盘Inode使用率",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by(device) (node_filesystem_avail_bytes{device=~\"/dev/.*\", instance=\"$Node\"} / node_filesystem_size_bytes{device=~\"/dev/.*\", instance=\"$Node\"}) * 100",
     "legendFormat": "{{device}}.space"
    },
    {
     "expr": "100 - avg by(device) (node_filesystem_files_free{device=~\"/dev/.*\", instance=\"$Node\"} / node_filesystem_files{device=~\"/dev/.*\", instance=\"$Node\"}) * 100",
     "legendFormat": "{{device}}.inode"
    }
   ]
  },
  {
   "title": "Disk IO Rate",
   "type": "graph",
   "description": "当前主机的磁盘读写磁盘的速度",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg by (instance,device) (node_disk_bytes_read_irate5m{instance=\"$Node\"})",
     "legendFormat": "{{device}}.read"
    },
    {
     "expr": "avg by (instance,device) (node_disk_bytes_written_irate5m{instance=\"$Node\"})",
     "legendFormat": "{{device}}.written"
    }
   ]
  },
  {
   "title": "Disk IO Time",
   "type": "graph",
   "description": "当前主机的磁盘IO Time，即是主机每秒中花在磁盘读写上的时间",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by (instance,device) (rate(node_disk_io_time_ms{instance=\"$Node\"}[2m]))",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Received Rate",
   "type": "graph",
   "description": "当前主机网卡过去5分钟接收数据的平均速度",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes{instance=\"$Node\",device!~\"lo|veth.*\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Transmitted Rate",
   "type": "graph",
   "description": "当前主机网卡过去5分钟发送数据的平均速度",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes{instance=\"$Node\",device!~\"lo|veth.*\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}