{
 "title": "Nodes Overview",
 "description": "Dashboard to get an overview of all nodes in a Kubernetes Cluster",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Node CPU Utilization",
   "type": "graph",
   "description": "当前集群中所有主机的CPU使用率",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - avg by (instance) (rate(node_cpu{mode=\"idle\"}[2m])) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Memory Utilization",
   "type": "graph",
   "description": "当前集群主机的内存使用率",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum by (instance) (node_memory_MemTotal) - sum by (instance) (node_memory_MemFree) - sum by (instance) (node_memory_Buffers) - sum by (instance) (node_memory_Cached)) / sum by (instance) (node_memory_MemTotal) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Normal System Load",
   "type": "graph",
   "description": "当前集群中所有主机的负载，正则化的计算方法是用主机的负载除以CPU核心数",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg by (host) (label_replace(node_load1, \"host\", \"$1\", \"instance\", \"(.*):.*\")) / avg by (host) (label_replace(machine_cpu_cores, \"host\", \"$1\", \"instance\", \"(.*):.*\")) ",
     "legendFormat": "{{host}}.load.1m"
    },
    {
     "expr": "avg by (host) (label_replace(node_load5, \"host\", \"$1\", \"instance\", \"(.*):.*\")) / avg by (host) (label_replace(machine_cpu_cores, \"host\", \"$1\", \"instance\", \"(.*):.*\")) ",
     "legendFormat": "{{host}}.load.5m"
    },
    {
     "expr": "avg by (host) (label_replace(node_load15, \"host\", \"$1\", \"instance\", \"(.*):.*\")) / avg by (host) (label_replace(machine_cpu_cores, \"host\", \"$1\", \"instance\", \"(.*):.*\")) ",
     "legendFormat": "{{host}}.load.15m"
    }
   ]
  },
  {
   "title": "Node Disk Space Utilization",
   "type": "graph",
   "description": "当前集群中所有主机的磁盘空间占用率",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by(instance, device) (node_filesystem_avail_bytes{device=~\"/dev/.*\"} / node_filesystem_size_bytes{device=~\"/dev/.*\"}) * 100",
     "legendFormat": "{{instance}}{{device}}"
    }
   ]
  },
  {
   "title": "Node Disk IO Time",
   "type": "graph",
   "description": "当前集群中所有主机的IO Time，是指主机每秒中花在磁盘读写上的时间",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by (instance, device) (node_disk_io_time_ms_irate5m{})",
     "legendFormat": "{{instance}}.{{device}}"
    }
   ]
  },
  {
   "title": "Node Disk Read Speed",
   "type": "graph",
   "description": "当前集群中所有主机的磁盘读取速度",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg by (instance, device) (rate(node_disk_bytes_read{}[5m]))",
     "legendFormat": "{{instance}}.{{device}}"
    }
   ]
  },
  {
   "title": "Node Disk Written Speed",
   "type": "graph",
   "description": "当前集群中所有主机的写磁盘速度",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg by (instance, device) (rate(node_disk_bytes_written{}[5m]))",
     "legendFormat": "{{instance}}.{{device}}"
    }
   ]
  },
  {
   "title": "Node Network Received Rate",
   "type": "graph",
   "description": "当前集群中所有主机的网卡过去5分钟接收流量的平均速度",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, device) (rate(node_network_receive_bytes{device=~\"eth.*\"}[5m]))",
     "legendFormat": "{{instance}}.{{device}}"
    }
   ]
  },
  {
   "title": "Node Network Transmitted Rate",
   "type": "graph",
   "description": "当前集群所有主机的网卡过去5分钟发送数据的平均速度",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, device) (rate(node_network_transmit_bytes{device=~\"eth.*\"}[5m]))",
     "legendFormat": "{{instance}}.{{device}}"
    }
   ]
  }
 ]
}