#!/usr/bin/bash

if [[ $# -gt 0 ]];then
    rm -rf ./ethbase/*
    geth --datadir "./ethbase" init genesis.json

    if [[ "$1" == "snew" || "$1" == "sn" ]];then
        geth --identity "myeth" --networkid 111 --nodiscover --maxpeers 10 --port "30303"  --rpc --rpcapi "db,eth,net,web3,personal,miner,admin,debug" --rpcaddr 0.0.0.0 --rpcport "8545" --ws --wsaddr 0.0.0.0 --wsorigins=* --wsapi "db,eth,net,web3,personal,miner,admin,debug" --wsport "8546" --datadir "./ethbase" console 2> geth.log << EOF
personal.newAccount('test')
eth.accounts

miner.setEtherbase(eth.accounts[0])
eth.coinbase
miner.start(2);admin.sleepBlocks(3);miner.stop()

web3.fromWei(eth.getBalance(eth.accounts[0]), 'ether')

eth.blockNumber
EOF
    exit
    else
        geth --identity "myeth" --networkid 111 --nodiscover --maxpeers 10 --port "30303"  --rpc --rpcapi "db,eth,net,web3,personal,miner,admin,debug" --rpcaddr 0.0.0.0 --rpcport "8545" --ws --wsaddr 0.0.0.0 --wsorigins=* --wsapi "db,eth,net,web3,personal,miner,admin,debug" --wsport "8546" --datadir "./ethbase" console 2> geth.log << EOF
personal.newAccount('test')
personal.newAccount('test')
personal.newAccount('test')
eth.accounts

miner.setEtherbase(eth.accounts[0])
eth.coinbase
miner.start(2);admin.sleepBlocks(10);miner.stop()

web3.fromWei(eth.getBalance(eth.accounts[0]), 'ether')
web3.fromWei(eth.getBalance(eth.accounts[1]), 'ether')
web3.fromWei(eth.getBalance(eth.accounts[2]), 'ether')

personal.unlockAccount(eth.accounts[0], 'bcfan', 600)
eth.getTransaction(eth.sendTransaction({from:eth.accounts[0], to:eth.accounts[1], value: web3.toWei(3, 'ether')}))
eth.getTransaction(eth.sendTransaction({from:eth.accounts[0], to:eth.accounts[2], value: web3.toWei(1, 'ether')}))

txpool.status
miner.start(2);admin.sleepBlocks(1);miner.stop()
txpool.status

web3.fromWei(eth.getBalance(eth.accounts[0]), 'ether')
web3.fromWei(eth.getBalance(eth.accounts[1]), 'ether')
web3.fromWei(eth.getBalance(eth.accounts[2]), 'ether')

eth.blockNumber
eth.getBlock(10)
eth.getTransactionFromBlock(11)
eth.getTransactionCount(eth.accounts[0], 'pending')
EOF
    fi
fi

geth --identity "myeth" --networkid 111 --nodiscover --maxpeers 10 --port "30303" --rpc --rpcapi "db,eth,net,web3,personal,miner,admin,debug" --rpcaddr 0.0.0.0 --rpcport "8545" --ws --wsaddr 0.0.0.0 --wsorigins=* --wsapi "db,eth,net,web3,personal,miner,admin,debug" --wsport "8546" --datadir "./ethbase" console 2>> geth.log


