{
 "title": "Kubernetes Cluster Status",
 "description": "Cluster level overview of workloads deployed, based on prometheus metrics exposed by kubelet, node-exporter, nginx ingress controller",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Control Plane Status",
   "type": "singlestat",
   "description": "当前集群控制组件的状态，包括kube-apiserver、kube-scheduler、kube-controller-manager；全部正常则是UP状态，否则是DOWN状态",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{job=~\"apiserver|kube-scheduler|kube-controller-manager\"})"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage",
   "type": "singlestat",
   "description": "当前集群的CPU使用率",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "percentunit",
   "valueName": "min",
   "targets": [
    {
     "expr": "cluster_cpu_utilization/count(avg by(instance,cpu)(node_cpu{job=\"node-exporter\",mode=\"idle\"}))"
    }
   ]
  },
  {
   "title": "Cluster Mem Usage",
   "type": "singlestat",
   "description": "当前集群的内存使用率",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "percentunit",
   "valueName": "min",
   "targets": [
    {
     "expr": "cluster_memory_MemUsed/sum(node_memory_MemTotal)"
    }
   ]
  },
  {
   "title": "Cluster CPU Requests",
   "type": "singlestat",
   "description": "当前集群的CPU Requests使用率",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "percentunit",
   "valueName": "min",
   "targets": [
    {
     "expr": "cluster_resource_requests_cpu_cores / sum(kube_node_status_allocatable_cpu_cores)"
    }
   ]
  },
  {
   "title": "Cluster Mem Requests",
   "type": "singlestat",
   "description": "当前集群的Kubernetes Memory Requests使用率",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "percentunit",
   "valueName": "min",
   "targets": [
    {
     "expr": "cluster_resource_requests_memory_bytes / sum(kube_node_status_allocatable_memory_bytes)"
    }
   ]
  },
  {
   "title": "Firing Alerts",
   "type": "singlestat",
   "description": "当前集群处于告警状态的告警数",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\"}) or on() vector(0)"
    }
   ]
  },
  {
   "title": "Request Time",
   "type": "singlestat",
   "description": "当前集群过去10分钟API Server的平均延迟",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(irate(apiserver_request_count[10m]))"
    }
   ]
  },
  {
   "title": "Request Error Rate",
   "type": "singlestat",
   "description": "当前集群过去10分钟API Server的请求发生错误的比例",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1-sum(rate(apiserver_request_count{code=~\"2..\"}[10m]))/sum (rate(apiserver_request_count[10m]))"
    }
   ]
  },
  {
   "title": "Min Idle CPU",
   "type": "singlestat",
   "description": "当前集群所有主机中，Idle CPU最小的主机的Idle CPU占比",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "format": "percentunit",
   "valueName": "min",
   "targets": [
    {
     "expr": "sort_desc(min(avg(rate(node_cpu{mode=\"idle\"}[1m])) by (instance)))"
    }
   ]
  },
  {
   "title": "Min Available Mem",
   "type": "singlestat",
   "description": "当前集群中所有主机中，可用内存最小的主机的可用内存占比",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Min Available Disk",
   "type": "singlestat",
   "description": "当前集群所有主机中，可用磁盘占比最小的主机的可用磁盘占用率（指的是主机的根目录）",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(node_filesystem_avail_bytes{mountpoint!~\".*(serviceaccount|proc|sys).*\"}/node_filesystem_size_bytes{mountpoint!~\".*(serviceaccount|proc|sys).*\"})"
    }
   ]
  },
  {
   "title": "Pods Restarted",
   "type": "singlestat",
   "description": "过去10分钟内发生过重启的Pod的个数",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum by (pod)(delta(kube_pod_container_status_restarts_total[10m]) > 0))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods Restarted",
   "type": "graph",
   "description": "过去15分钟内发生过重启的Pod列表，以及每个Pod重启的次数的列表",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum by (pod)(delta(kube_pod_container_status_restarts_total[15m]) > 0))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods Status",
   "type": "graph",
   "description": "当前集群中所有Pod的状态",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{}) by (phase)",
     "legendFormat": "{{ phase }}"
    },
    {
     "expr": "kubelet_running_pod_count{kubernetes_io_role =~ \".*node.*\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Kubernetes API  Servers Latency",
   "type": "graph",
   "description": "过去10分钟内API Server的请求延迟",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by(instance, verb)(irate(apiserver_request_latencies_count{verb=~\"GET|PUT|POST|PATCH|DELETE\"}[10m]))",
     "legendFormat": "{{instance}}.{{verb}}"
    }
   ]
  },
  {
   "title": "Kubernetes API  Servers Request Result",
   "type": "graph",
   "description": "过去10分钟内API Server的请求返回码统计",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (rate(apiserver_request_count{code=~\"2..\"}[10m]))",
     "legendFormat": "{{instance}}.2XX"
    },
    {
     "expr": "sum by(instance) (rate(apiserver_request_count{code=~\"4..\"}[10m]))",
     "legendFormat": "{{instance}}.4XX"
    },
    {
     "expr": "sum by(instance) (rate(apiserver_request_count{code=~\"5..\"}[10m]))",
     "legendFormat": "{{instance}}.5XX"
    },
    {
     "expr": "sum by(instance) (rate(apiserver_request_count[10m]))",
     "legendFormat": "{{instance}}.Total"
    }
   ]
  },
  {
   "title": "Node CPU Idle",
   "type": "graph",
   "description": "当前集群中所有主机的Idle CPU占比",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu{mode=\"idle\"}[1m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Node Memory Available",
   "type": "graph",
   "description": "当前集群中所有主机可用内存占比",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemFree + node_memory_Buffers + node_memory_Cached)/node_memory_MemTotal",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Storage",
   "type": "graph",
   "description": "当前集群中所有主机根目录的磁盘使用率",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "min(1-node_filesystem_avail_bytes{mountpoint!~\".*(serviceaccount|proc|sys).*\", device!=\"overlay\"}/node_filesystem_size_bytes{mountpoint!~\".*(serviceaccount|proc|sys).*\", device!=\"overlay\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Load",
   "type": "graph",
   "description": "当前集群中所有主机的负载，包括过去1分钟、5分钟、15分钟",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "{{instance}}.1m" },
    { "expr": "node_load5", "legendFormat": "{{instance}}.5m" },
    { "expr": "node_load15", "legendFormat": "{{instance}}.15m" }
   ]
  },
  {
   "title": "Node Conditions",
   "type": "graph",
   "description": "集群中所有主机的状态，主要有Ready/DiskPressure等等",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_node_status_condition{status=\"true\"} > 0",
     "legendFormat": "{{node}}.{{condition}}"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "description": "当前集群中所有主机磁盘的IO时间",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_disk_io_time_ms[1m]))",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Pods  CPU Utilization > 80%",
   "type": "graph",
   "description": "过去5分钟内Pod的CPU 利用率大于80%的Pod列表（如果没有数据，则证明集群内Pod的CPU压力较小，可以根据实际情况调整阈值）",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(namespace, pod_name) (rate(container_cpu_usage_seconds_total{container_name!=\"POD\"}[5m])) / sum by(namespace, pod_name) (container_spec_cpu_quota{container_name!=\"POD\"}) * 100000 > 0.8",
     "legendFormat": "{{namespace}}.{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pods  Memory Utilization > 80%",
   "type": "graph",
   "description": "过去5分钟内Pod的内存利用率大于80%的Pod列表",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(pod_name, namespace) (container_memory_usage_bytes_without_cache{namespace!=\"\", container_name!=\"POD\"}) / sum by(pod_name, namespace) (container_spec_memory_limit_bytes{namespace!=\"\", container_name!=\"POD\"}) > 0.8",
     "legendFormat": "{{namespace}}.{{pod_name}}"
    }
   ]
  },
  {
   "title": "TOP 5 CPU Intense Pods",
   "type": "graph",
   "description": "当前集群中占用CPU最多的5个Pod，单位Core",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5,sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[5m])) by (pod_name))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Top 5 Memory Intense Pods",
   "type": "graph",
   "description": "当前集群中占用内存最多的5个Pod",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(5,sum(container_memory_usage_bytes{image!=\"\"}) by (pod_name))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Cluster Unusual Event",
   "type": "table",
   "description": "集群中当前存在的异常事件列表[add]",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(kubernetes_events{event_type!=\"Normal\"}) by (event_kind, event_name, event_namespace, event_type, event_message)"
    }
   ]
  }
 ]
}