{
 "title": "Kubernetes StatefulSet Status",
 "description": "Kubernetes StatefulSet Status",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "statefulset_namespace",
    "label": "Namespace",
    "query": "label_values(kube_statefulset_metadata_generation, namespace)"
   },
   {
    "name": "statefulset_name",
    "label": "StatefulSet",
    "query": "label_values(kube_statefulset_metadata_generation{namespace=\"$statefulset_namespace\"}, statefulset)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "singlestat",
   "description": "当前StatefulSet的Pod的CPU使用率，平均值",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{namespace=\"$statefulset_namespace\",pod_name=~\"$statefulset_name-[0-9]{1,3}\", image!=\"\",container_name!=\"POD\"}[3m]))) / (sum(container_spec_cpu_quota{namespace=\"$statefulset_namespace\",pod_name=~\"$statefulset_name-[0-9]{1,3}\", image!=\"\",container_name!=\"POD\"}/100000))",
     "legendFormat": "pod_restart_count"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "singlestat",
   "description": "当前StatefulSet的Pod的Memory使用率",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum (container_memory_usage_bytes_without_cache{namespace=\"$statefulset_namespace\",pod_name=~\"$statefulset_name-[0-9]{1,3}\"}))/(sum (container_spec_memory_limit_bytes{namespace=\"$statefulset_namespace\",pod_name=~\"$statefulset_name-[0-9]{1,3}\", image!=\"\",container_name!=\"POD\"}))",
     "legendFormat": "pod_restart_count"
    }
   ]
  },
  {
   "title": "Health",
   "type": "singlestat",
   "description": "当前StatefulSet的健康状态，即当前处于运行状态的Pod在所有Pod中的占比",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum (kube_pod_status_phase{namespace=\"$statefulset_namespace\",pod=~\"$statefulset_name-[0-9]{1,3}\", phase=\"Running\"}))/(sum (kube_pod_status_phase{namespace=\"$statefulset_namespace\",pod=~\"$statefulset_name-[0-9]{1,3}\"}))",
     "legendFormat": "pod_restart_count"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "singlestat",
   "description": "当前健康的实例数",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{namespace=\"$statefulset_namespace\",pod=~\"$statefulset_name-[0-9]{1,3}\", phase=\"Running\"})",
     "legendFormat": "pod_restart_count"
    }
   ]
  },
  {
   "title": "Not Running Pods",
   "type": "singlestat",
   "description": "当前StatefulSet非运行状态的实例数",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{namespace=\"$statefulset_namespace\",pod=~\"$statefulset_name-[0-9]{1,3}\", phase!=\"Running\"})",
     "legendFormat": "pod_restart_count"
    }
   ]
  },
  {
   "title": "Pods Restarted",
   "type": "singlestat",
   "description": "过去15分钟内Pod重启的次数",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (delta(kube_pod_container_status_restarts_total{namespace=\"$statefulset_namespace\",pod=~\"$statefulset_name-[0-9]{1,3}\"}[15m]))",
     "legendFormat": "pod_restart_count"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "当前StatefulSet的CPU使用情况，单位Core",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (rate(container_cpu_usage_seconds_total{namespace=\"$statefulset_namespace\",pod_name=~\"$statefulset_name-[0-9]{1,3}\", image!=\"\",container_name!=\"POD\"}[3m]))",
     "legendFormat": "{{pod_name}}.cpu_usage"
    },
    {
     "expr": "avg (container_spec_cpu_quota{namespace=\"$statefulset_namespace\",pod_name=~\"$statefulset_name-[0-9]{1,3}\", image!=\"\",container_name!=\"POD\"}/100000)",
     "legendFormat": "cpu_quota"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "当前StatefulSet的Memory使用情况",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name)(container_memory_usage_bytes_without_cache{namespace=\"$statefulset_namespace\",pod_name=~\"$statefulset_name-[0-9]{1,3}\"})",
     "legendFormat": "{{pod_name}}.memory_usage"
    },
    {
     "expr": "avg (container_spec_memory_limit_bytes{namespace=\"$statefulset_namespace\",pod_name=~\"$statefulset_name-[0-9]{1,3}\", image!=\"\",container_name!=\"POD\"})",
     "legendFormat": "memory_quota"
    }
   ]
  },
  {
   "title": "Pods Status",
   "type": "graph",
   "description": "当前StatefulSet所有Pod的状态",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_status_phase{namespace=\"$statefulset_namespace\",pod=~\"$statefulset_name-[0-9]{1,3}\"} > 0",
     "legendFormat": "{{pod}}.{{ phase }}"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_current{statefulset=\"$statefulset_name\",namespace=\"$statefulset_namespace\"}",
     "legendFormat": "current replicas"
    },
    {
     "expr": "kube_statefulset_status_replicas_ready{statefulset=\"$statefulset_name\",namespace=\"$statefulset_namespace\"}",
     "legendFormat": "ready replicas"
    },
    {
     "expr": "kube_statefulset_status_replicas_updated{statefulset=\"$statefulset_name\",namespace=\"$statefulset_namespace\"}",
     "legendFormat": "updated replicas"
    },
    {
     "expr": "kube_statefulset_status_replicas{statefulset=\"$statefulset_name\",namespace=\"$statefulset_namespace\"}",
     "legendFormat": "replicas"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "description": "当前StatefulSet的网络流量情况",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (rate(container_network_receive_bytes_total{namespace=\"$statefulset_namespace\",pod_name=~\"$statefulset_name-[0-9]{1,3}\"}[5m]))",
     "legendFormat": "{{pod_name}}.network_received"
    },
    {
     "expr": "sum by (pod_name) (rate(container_network_transmit_bytes_total{namespace=\"$statefulset_namespace\",pod_name=~\"$statefulset_name-[0-9]{1,3}\"}[5m]))",
     "legendFormat": "{{pod_name}}.network_transmitted"
    }
   ]
  }
 ]
}