{
 "title": "Kubernetes Cluster Health",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Control Plane UP",
   "type": "singlestat",
   "description": "当前集群的控制组件的状态，包括API Server、Controller Manager和Scheduler，只有三个组件都正常才会显示为UP，其它情况显示的是不正常的组件数",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": " sum(up{job=~\"apiserver|kube-scheduler|kube-controller-manager\"})-sum(up{job=~\"apiserver|kube-scheduler|kube-controller-manager\"} == 1)"
    }
   ]
  },
  {
   "title": "Alerts Firing",
   "type": "singlestat",
   "description": "当前集群处于告警状态的告警数",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\"}) or on() vector(0)"
    }
   ]
  },
  {
   "title": "API Servers UP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(up{job=\"apiserver\"} == 1) / count(up{job=\"apiserver\"})) * 100"
    }
   ]
  },
  {
   "title": "Controller Managers UP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(up{job=\"kube-controller-manager\"} == 1) / count(up{job=\"kube-controller-manager\"})) * 100"
    }
   ]
  },
  {
   "title": "Schedulers UP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(up{job=\"kube-scheduler\"} == 1) / count(up{job=\"kube-scheduler\"})) * 100"
    }
   ]
  },
  {
   "title": "Docker UP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(engine_daemon_engine_info) or on() vector(0))/ count(node_uname_info) * 100"
    }
   ]
  },
  {
   "title": "API Servers UP",
   "type": "graph",
   "description": "API Servers的状态",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"apiserver\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Controller Managers UP",
   "type": "graph",
   "description": "Controller Managers的状态",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"kube-controller-manager\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Schedulers UP",
   "type": "graph",
   "description": "Schedulers的状态",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"kube-scheduler\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Docker UP",
   "type": "graph",
   "description": "Docker的状态",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "engine_daemon_engine_info", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "DNS UP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(up{job=\"kube-dns\"} == 1) / count(up{job=\"kube-dns\"})) * 100"
    }
   ]
  },
  {
   "title": "ETCD UP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(up{job=\"kube-etcd\"} == 1) / count(up{job=\"kube-etcd\"})) * 100"
    }
   ]
  },
  {
   "title": "Kubelet UP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(up{job=\"kubelet\"} == 1) / count(up{job=\"kubelet\"})) * 100"
    }
   ]
  },
  {
   "title": "Kube Proxy UP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(up{job=\"kube-proxy\"} == 1) / count(up{job=\"kube-proxy\"})) * 100"
    }
   ]
  },
  {
   "title": "DNS UP",
   "type": "graph",
   "description": "Kube DNS的状态",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"kube-dns\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ETCD UP",
   "type": "graph",
   "description": "ETCD的状态",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"kube-etcd\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Kubelet UP",
   "type": "graph",
   "description": "Kubelet的状态",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"kubelet\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Kube Proxy UP",
   "type": "graph",
   "description": "Kube Proxy的状态",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"kube-proxy\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Ready",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 22 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"})/sum(kube_node_status_condition{condition=\"Ready\"})"
    }
   ]
  },
  {
   "title": "Node Ready",
   "type": "graph",
   "description": "Node的状态",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (node) (kube_node_status_condition{condition=\"Ready\",status=\"true\"})",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}