{
 "title": "Kubernetes Pod Status",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "graph",
   "description": "Pod的CPU使用率",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(pod_name) (rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",pod_name=~\"$pod\",container_name!=\"POD\"}[5m])) / sum by(pod_name) (container_spec_cpu_quota{namespace=~\"$namespace\",pod_name=~\"$pod\",container_name!=\"POD\"}) * 100000",
     "legendFormat": " {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "description": "Pod的内存使用率",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(pod_name) (container_memory_usage_bytes{namespace=~\"$namespace\",pod_name=~\"$pod\",image!=\"\", container_name!=\"POD\"}) / sum by(pod_name) (container_spec_memory_limit_bytes{namespace=~\"$namespace\",pod_name=~\"$pod\",image!=\"\",container_name!=\"POD\"})",
     "legendFormat": " {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "graph",
   "description": "Pod的运行状态",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_status_phase{namespace=~\"$namespace\",pod=~\"$pod\",container_name!=\"POD\"} > 0",
     "legendFormat": " {{ pod }}.{{phase}}"
    }
   ]
  },
  {
   "title": "Netwrok IO",
   "type": "graph",
   "description": "Pod的Network IO状态",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg by(pod_name) (irate(container_network_receive_bytes_total{namespace=~\"$namespace\",pod_name=~\"$pod\"}[5m])) ",
     "legendFormat": " {{ pod_name }}"
    }
   ]
  }
 ]
}